// 动效缩略图语义图标：把动效的元数据收敛到一个可复用的图标 key。
// 只做纯推导，不依赖 React、DOM 或 Tauri，便于测试与复用。
import type { CompositionDefinition } from "@/domain/effects";
import { shotcraftShot } from "@/domain/shotcraft";

export const EFFECT_GLYPH_KEYS = [
  "camera-push", "camera-pull", "camera-pan", "camera-tilt", "camera-orbit", "camera-depth", "camera-travel", "camera-overhead", "camera-freeze", "camera-frame", "camera-reticle",
  "type-typewriter", "type-assemble", "type-underline", "type-highlight", "type-fill", "type-glitch", "type-flip", "type-mask", "type-roll", "type-outline", "type-stretch", "type-path", "type-count", "type-quote", "type-marquee", "type-caption", "type-bracket",
  "data-counter", "data-bar", "data-ring", "data-line", "data-gauge", "data-grid", "data-odometer", "data-timeline", "data-rank",
  "transition-wipe", "transition-flash", "transition-iris", "transition-cube", "transition-page", "transition-glitch", "transition-cut", "transition-mask", "transition-travel",
  "ui-stack", "ui-grid", "ui-list", "ui-panel", "ui-morph", "ui-skeleton", "ui-cursor", "ui-pill", "ui-window", "ui-select", "ui-dial", "ui-key", "ui-carousel", "ui-segment", "ui-card", "ui-flip", "ui-compare", "ui-scatter", "ui-terminal",
  "light-glow", "light-sweep", "light-spot", "light-particle", "light-ripple", "light-flyline",
  "effect-impact", "effect-bounce", "effect-print", "effect-motion-blur",
  "shape-draw", "shape-fracture", "shape-hub",
  "rhythm-beat", "rhythm-montage", "rhythm-speed", "rhythm-strobe",
  "person-avatar", "person-chat", "brand-logo", "brand-frame", "annotate-mark",
  "background-texture", "background-photo", "background-glass", "background-scene", "scene-3d",
  "media-audio"
] as const;

export type EffectGlyphKey = (typeof EFFECT_GLYPH_KEYS)[number];

/** 动效 id 级覆盖：语义独特的动效优先于其所属配方卡。 */
const effectIdGlyphs: Readonly<Record<string, EffectGlyphKey>> = {
  "quote-lockup": "type-quote",
  "step-timeline": "data-timeline",
  "rank-bars": "data-rank",
  "punch-pill": "type-highlight",
  "term-card": "ui-card",
  "pin-board": "ui-card",
  checklist: "ui-list",
  "terminal-3d": "ui-terminal",
  "ring-metric": "data-ring",
  "versus-card": "ui-compare",
  "ui-callout": "annotate-mark",
  "type-shift": "type-assemble",
  "blur-text": "type-assemble",
  odometer: "data-odometer",
  "focus-card": "person-avatar",
  "chapter-bar": "data-timeline",
  "caption-track": "type-caption",
  "entity-chips": "ui-pill",
  "stat-proof": "data-counter",
  "growth-curve": "data-line",
  "poster-wall-3d": "background-photo",
  "image-duet-3d": "ui-compare",
  "motion-zoom": "camera-push",
  "slide-gallery": "ui-carousel",
  "card-stack": "ui-stack",
  "split-reveal": "transition-wipe",
  "still-image-motion": "background-photo",
  "background-stripes": "background-texture",
  "background-grid": "background-texture",
  "background-dots": "background-texture",
  "background-contours": "background-texture",
  "shotcraft-blur-slide": "type-assemble",
  "shotcraft-before-after": "ui-compare",
  "shotcraft-cursor-flyover": "ui-cursor",
  "shotcraft-basic-3d": "camera-travel",
  "shotcraft-spotlight-hero-card": "light-spot",
  "shotcraft-card-stack": "ui-stack",
  "shotcraft-tilt-reveal": "camera-tilt",
  "shotcraft-drone-dive-landing": "camera-travel",
  "shotcraft-exploded-view": "camera-depth",
  "shotcraft-bullet-time-freeze-orbit": "camera-orbit",
  "shotcraft-dutch-roll-to-level": "camera-tilt",
  "shotcraft-pull-back-isolation": "camera-pull",
  "shotcraft-slow-push-in": "camera-push",
  "shotcraft-axis-rescale-shock-v2": "data-bar",
  "shotcraft-oscilloscope-stream-v2": "data-line",
  "shotcraft-unit-dot-swarm-regroup-v2": "data-grid",
  "shotcraft-counter-tick-sparks": "data-counter",
  "shotcraft-brake-reticle-lock": "camera-reticle",
  "shotcraft-changelog-scroll-brake": "ui-list",
  "shotcraft-line-unfold-panel": "ui-panel",
  "shotcraft-reticle-lock-on": "camera-reticle",
  "shotcraft-flyline-arc": "light-flyline",
  "shotcraft-glow-orb-ambient": "light-glow",
  "shotcraft-orb-flyline-relay": "light-flyline",
  "shotcraft-halation-bloom": "light-glow",
  "shotcraft-sheen-sweep-retry": "light-sweep",
  "shotcraft-spotlight-sweep-reveal": "light-spot",
  "shotcraft-impact-burst-kit": "effect-impact",
  "shotcraft-kanada-perspective-snap": "camera-tilt",
  "shotcraft-score-slam": "data-counter",
  "shotcraft-corner-spotlight-reveal": "light-spot",
  "shotcraft-glow-wake-sleep-panel": "light-sweep",
  "shotcraft-slide-spotlight-pan": "camera-pan",
  "shotcraft-palette-theme-ripple": "light-ripple",
  "shotcraft-theme-sweep-toggle": "light-sweep",
  "shotcraft-letterform-drift-assembly": "type-assemble",
  "shotcraft-split-text-stagger": "type-assemble",
  "shotcraft-text-on-path": "type-path",
  "shotcraft-tracking-expand-reveal": "type-stretch",
  "shotcraft-letter-drop-physics": "type-assemble",
  "shotcraft-scramble-decode": "type-glitch",
  "shotcraft-font-weight-pump": "type-stretch",
  "shotcraft-karaoke-fill-sync": "type-fill",
  "shotcraft-terminal-typewriter": "type-typewriter",
  "shotcraft-typewriter-error-retype": "type-typewriter",
  "shotcraft-axial-stretch": "type-stretch",
  "shotcraft-contact-shadow-lift": "ui-card",
  "shotcraft-masking-tape-slap": "ui-card",
  "shotcraft-popup-book-rise": "ui-card",
  "shotcraft-bento-light-up": "ui-grid",
  "shotcraft-grid-wave-flip": "ui-grid",
  "shotcraft-wireframe-draw-on": "shape-draw",
  "shotcraft-beat-cut-accelerando": "transition-cut",
  "shotcraft-paparazzi-flash": "transition-flash",
  "shotcraft-domino-cascade": "ui-stack",
  "shotcraft-drop-blackout-slam": "rhythm-strobe",
  "shotcraft-wright-triple-cut": "rhythm-montage",
  "shotcraft-comic-panel-split": "rhythm-montage",
  "shotcraft-flip-grid-reflow": "ui-grid",
  "shotcraft-grid-flash-mosaic": "ui-grid",
  "shotcraft-jump-cut-punch-in": "camera-push",
  "shotcraft-strobe-black-frames": "rhythm-strobe",
  "shotcraft-card-footage-cadence": "rhythm-montage",
  "shotcraft-smash-cut": "transition-cut",
  "shotcraft-trailer-bumper": "rhythm-montage",
  "shotcraft-barn-door-split": "transition-wipe",
  "shotcraft-cube-rotate": "transition-page",
  "shotcraft-black-card-transition": "transition-cut",
  "shotcraft-dark-tunnel-transition": "transition-travel",
  "shotcraft-focus-handoff-transition": "camera-reticle",
  "shotcraft-mask-wipe-real": "transition-mask",
  "shotcraft-portal-wipe-v2": "transition-iris",
  "shotcraft-whip-brake-real": "transition-wipe",
  "shotcraft-whip-pan-real": "transition-wipe",
  "shotcraft-invisible-cut": "transition-mask",
  "shotcraft-light-leak-burn": "transition-flash",
  "shotcraft-versus-slam": "transition-wipe",
  "shotcraft-letterform-zoom": "type-mask",
  "shotcraft-shared-element-morph": "transition-travel",
  "shotcraft-confetti-crossfire": "light-particle",
  "proof-shot": "background-photo",
  "multiply-grid": "ui-grid",
  "stair-bars": "data-bar",
  "quote-cite": "type-quote",
  "formula-pill": "type-highlight",
  "kinetic-words": "type-assemble",
  "chat-volley": "person-chat",
  "action-band": "ui-panel",
  "timeline-h": "data-timeline",
  "section-head": "type-assemble",
  "icon-swarm": "ui-grid",
  "stroke-title": "type-outline",
  "duo-title": "type-assemble",
  "chip-cluster": "ui-pill",
  "glow-badges": "light-glow",
  "map-territory": "shape-hub",
  "icon-pop": "effect-bounce",
  "steer-hint": "annotate-mark",
  "pain-points": "ui-card",
  "decrypt-text": "type-glitch",
  "word-flank": "type-assemble",
  "hand-lift": "person-avatar",
  "demo-rail": "scene-3d",
  "project-window": "ui-panel"
};

/** Shotcraft 配方卡级覆盖：同一张卡的多个动效共享同一语义。 */
const shotcraftCardGlyphs: Readonly<Record<string, EffectGlyphKey>> = {
  "shot-transitions": "transition-cut",
  "tension-camera-moves": "camera-push",
  "type-assembly-moves": "type-assemble",
  "chart-live-moves": "data-bar",
  "glow-flyline-moves": "light-flyline",
  "light-play-moves": "light-glow",
  "slam-entrance-moves": "effect-impact",
  "spotlight-sweep-moves": "light-spot",
  "montage-rhythm-moves": "rhythm-montage",
  "panel-grid-moves": "ui-grid",
  "trailer-grammar-moves": "rhythm-montage",
  "transition-hidden-cut": "transition-mask",
  "wall-reveal-moves": "ui-grid",
  "crash-zoom-punch": "camera-push",
  "depth-layer-moves": "camera-depth",
  "overhead-camera-moves": "camera-overhead",
  "space-camera-moves": "camera-travel",
  "gauge-readout-moves": "data-gauge",
  "particle-celebrate-hits": "light-particle",
  "scroll-brake-moves": "ui-list",
  "fui-hud-moves": "ui-panel",
  "icon-performance-moves": "effect-bounce",
  "impact-feedback": "effect-impact",
  "riso-print-hits": "effect-print",
  "canvas-materialize-moves": "ui-morph",
  "collab-cursor-moves": "ui-cursor",
  "input-trigger-moves": "ui-key",
  "theme-switch-moves": "light-sweep",
  "ui-to-brand-morph": "brand-logo",
  "beat-cut-moves": "transition-cut",
  "rhythm-interrupt-moves": "rhythm-strobe",
  "speed-ramp-freeze": "rhythm-speed",
  "page-turn-transitions": "transition-page",
  "transition-travel": "transition-travel",
  "wipe-transitions": "transition-wipe",
  "type-entrance-moves": "type-assemble",
  "type-rhythm-sync": "type-stretch",
  "typewriter-moves": "type-typewriter",
  "element-body-moves": "ui-card",
  "paper-craft-moves": "ui-card",
  "graze-face-tour": "camera-travel",
  "steep-tilt-glide": "camera-tilt",
  "terminal-3d": "camera-travel",
  "avatar-grid-radial-build-colorize": "ui-grid",
  "counter-confetti": "data-counter",
  "cycle-glass-node-morph": "ui-morph",
  "hatch-depth": "data-bar",
  "odometer-digit-roll": "data-odometer",
  "particle-sand-fill": "light-particle",
  "ring-diagram-annotation-reveal": "data-ring",
  "timeline-travel": "data-timeline",
  "assemble-then-type-flyin": "ui-skeleton",
  "aurora-bloom-bg-flip": "background-texture",
  "brand-frame-snap": "brand-frame",
  "dashboard-glow-highlight-pill": "ui-pill",
  "line-boil": "shape-draw",
  "radial-ripple-phone-chips": "light-ripple",
  "scan-bracket-sweep": "camera-frame",
  "scanline-annotate-focus": "annotate-mark",
  "scanline-assemble-flyin": "ui-skeleton",
  "ai-stream-response": "person-chat",
  "autolayout-gap-dial": "ui-dial",
  "chip-grid-single-select-blackout": "ui-select",
  "chip-lift-to-user-pill": "ui-pill",
  "command-palette-summon": "ui-panel",
  "glass-pill-dictation-typing": "type-typewriter",
  "hashtag-to-pill-materialize": "ui-pill",
  "picker-carousel-feature-cycle": "ui-carousel",
  "segmented-thumb-hero": "ui-segment",
  "type-and-filter": "type-typewriter",
  "voice-waveform-live": "media-audio",
  "crane-rise-reveal": "camera-travel",
  "dataviz-landscape-open": "data-grid",
  fracture: "shape-fracture",
  "icon-field-colorize": "ui-grid",
  "letterspace-materialize": "type-stretch",
  "magician-card-flourish": "ui-stack",
  "orbit-ring-title-open": "camera-orbit",
  "stroke-segment-build": "shape-draw",
  "text-as-mask": "type-mask",
  "edit-hook-moves": "brand-logo",
  "grain-dissolve": "light-particle",
  "logo-shrink-wordmark-lockup": "brand-logo",
  "neon-triple-marquee": "type-marquee",
  "outro-group-photo-launch": "background-photo",
  "ui-strip-away-outro": "ui-panel",
  "beat-step-list-theme-cycle": "ui-list",
  "quad-split-parallel-scenes": "rhythm-montage",
  "sakuga-timing-shift": "rhythm-speed",
  "smear-multiples": "effect-motion-blur",
  "spectrum-morph-ui": "media-audio",
  "bottom-push-stack-wipe": "transition-wipe",
  "bubble-swarm-takeover": "light-particle",
  "card-flip-reveal": "ui-flip",
  "card-flock-tumble": "ui-stack",
  "circle-match-iris": "transition-iris",
  "color-block-step-wipe": "transition-wipe",
  "cube-navigation": "transition-cube",
  "gradient-transition": "background-texture",
  "line-carry-transition": "transition-travel",
  "mosaic-reframe": "ui-grid",
  "paper-plane-messenger": "transition-travel",
  "print-texture-transitions": "effect-print",
  "tear-streak-transitions": "transition-glitch",
  "white-flash-logo-simplify-cut": "transition-flash",
  "brace-expand": "type-bracket",
  "brand-ink-open": "brand-logo",
  "cel-flash-stomp": "transition-flash",
  "countdown-arc-scatter": "type-count",
  "flying-words": "type-assemble",
  "glitch-cycle": "type-glitch",
  "gradient-word-sweep": "type-fill",
  "lead-word-zoom-assemble": "type-assemble",
  "marker-underline-title": "type-underline",
  "outline-word-fill": "type-outline",
  "paper-title-card": "ui-card",
  "pill-chip-slot-cycle-handled": "ui-pill",
  "pill-slot-cycle": "ui-pill",
  scramble: "type-glitch",
  "split-flap-title": "type-flip",
  "text-column-converge": "type-assemble",
  "title-demote-to-label": "type-assemble",
  "typing-code-block": "type-typewriter",
  "vertical-word-roll-blur-cycle": "type-roll",
  "word-relay-filmstrip": "type-roll",
  "word-relay-geometry": "type-roll",
  "document-typewriter-reveal": "type-typewriter",
  "avatar-bracket-carousel": "ui-carousel",
  "bezier-source-converge-merge": "light-flyline",
  "carousel-3d": "ui-carousel",
  "cloner-depth-echo": "ui-stack",
  "deck-deal-flyin": "ui-stack",
  "doc-park-left-pill-deal": "ui-pill",
  "draw-svg-trace": "shape-draw",
  "floating-glossy-label-pills": "ui-pill",
  "integration-hub-map": "shape-hub",
  "list-reveal": "ui-list",
  "list-stack-press": "ui-list",
  "morph-from-primitive": "ui-morph",
  "neon-frame-forerun": "brand-frame",
  "neon-frame-orbit-drop": "brand-frame",
  "page-waterfall-wall": "ui-grid",
  "platform-hinge-rise": "ui-card",
  "product-card-progressive-assemble": "ui-card",
  "radial-wave": "light-ripple",
  "research-card-stack-scroll": "ui-stack",
  "row-embed": "ui-list",
  "runway-ground-skim": "camera-travel",
  "skeleton-reveal": "ui-skeleton",
  "svg-shape-morph": "ui-morph",
  "value-stagger-gradient": "data-grid",
  "blur-slide": "type-assemble",
  "before-after-slider-scrub": "ui-compare",
  "cursor-flyover": "ui-cursor",
  "basic-3d-scene": "camera-travel",
  "spotlight-hero-card": "light-spot"
};

/** Overlay Studio 动效语汇（tags 里的语义标签）覆盖。 */
const overlayVocabularyGlyphs: Readonly<Record<string, EffectGlyphKey>> = {
  逐条落位: "ui-list",
  堆叠累积: "ui-stack",
  滚动计数: "data-counter",
  对撞并置: "ui-compare",
  翻转轮换: "ui-flip",
  扫过点亮: "light-sweep",
  聚散飞行: "ui-scatter",
  生长描画: "shape-draw",
  光效发光: "light-glow",
  粒子流场: "light-particle",
  玻璃虚化: "background-glass",
  "3D 浮屏": "scene-3d",
  推近定格: "camera-push",
  取景重构: "camera-frame",
  故障噪点: "transition-glitch"
};

const keywordGlyphs: readonly (readonly [RegExp, EffectGlyphKey])[] = [
  [/打字|typing|typewriter|键入/, "type-typewriter"],
  [/下划线|underline|马克笔/, "type-underline"],
  [/高亮|highlight|强调条|填色随读/, "type-highlight"],
  [/蒙版|遮罩字|文字蒙版/, "type-mask"],
  [/翻牌|翻页字|词槽|滚轮|跑马灯/, "type-roll"],
  [/乱码|故障字|噪点/, "type-glitch"],
  [/字距|字重|拉伸|stretch/, "type-stretch"],
  [/字幕|caption/, "type-caption"],
  [/倒计时|表盘|计时/, "type-count"],
  [/金句|引用|quote/, "type-quote"],
  [/环绕|orbit|旋转|rotat/, "camera-orbit"],
  [/推近|推镜|zoom in|急推|拉近/, "camera-push"],
  [/拉远|zoom out|退镜/, "camera-pull"],
  [/横摇|横移|平移|pan|摇镜/, "camera-pan"],
  [/俯仰|倾斜|tilt/, "camera-tilt"],
  [/分层|景深|纵深|depth/, "camera-depth"],
  [/俯视|桌面|overhead/, "camera-overhead"],
  [/定格|冻结|freeze/, "camera-freeze"],
  [/取景|画框取景|frame/, "camera-frame"],
  [/准星|十字|reticle|crosshair/, "camera-reticle"],
  [/计数|counter|滚动数字|数字滚动|里程/, "data-counter"],
  [/柱|条形|bar chart|排名条/, "data-bar"],
  [/环形|占比|donut|圆环/, "data-ring"],
  [/曲线|趋势|line chart|复利/, "data-line"],
  [/仪表|指针|gauge|刻度/, "data-gauge"],
  [/点阵|矩阵|grid|网格数据/, "data-grid"],
  [/时间线|timeline|甘特/, "data-timeline"],
  [/排名|rank/, "data-rank"],
  [/擦除|wipe|百叶|推走/, "transition-wipe"],
  [/闪白|漏光|flash|频闪/, "transition-flash"],
  [/光圈|iris|圆切/, "transition-iris"],
  [/立方体|cube/, "transition-cube"],
  [/翻页|page turn/, "transition-page"],
  [/硬切|cut|剪辑/, "transition-cut"],
  [/遮罩|mask/, "transition-mask"],
  [/穿越|穿行|travel|共享元素/, "transition-travel"],
  [/叠卡|堆叠|stack|发牌/, "ui-stack"],
  [/网格|grid|马赛克|瀑布墙/, "ui-grid"],
  [/清单|列表|list|步骤|逐项/, "ui-list"],
  [/面板|panel|侧栏/, "ui-panel"],
  [/变形|morph|物化|形状变化/, "ui-morph"],
  [/骨架|skeleton|占位/, "ui-skeleton"],
  [/光标|cursor|鼠标/, "ui-cursor"],
  [/胶囊|药丸|pill|名牌|标签/, "ui-pill"],
  [/窗口|window|浏览器/, "ui-window"],
  [/选中|单选|勾选|select/, "ui-select"],
  [/拨盘|滑块|间距|dial/, "ui-dial"],
  [/键帽|键盘|keycap/, "ui-key"],
  [/轮播|画廊|carousel/, "ui-carousel"],
  [/分段控件|segment/, "ui-segment"],
  [/卡片|card/, "ui-card"],
  [/翻转|flip/, "ui-flip"],
  [/对比|versus|对撞|前后/, "ui-compare"],
  [/聚散|飞散|散布|scatter/, "ui-scatter"],
  [/终端|terminal|命令行/, "ui-terminal"],
  [/光晕|发光|glow|光斑|光效/, "light-glow"],
  [/扫光|光影|斜扫|sweep/, "light-sweep"],
  [/聚光|spotlight|追光/, "light-spot"],
  [/粒子|particle|尘埃|纸屑|礼炮/, "light-particle"],
  [/涟漪|波纹|ripple/, "light-ripple"],
  [/飞线|连线|汇流|flyline/, "light-flyline"],
  [/冲击|打击|爆点|impact/, "effect-impact"],
  [/弹跳|bounce|跳动/, "effect-bounce"],
  [/孔版|印刷|墨渗|print/, "effect-print"],
  [/拖影|motion blur|残影/, "effect-motion-blur"],
  [/描线|描边|勾勒|draw/, "shape-draw"],
  [/碎片|fracture|飞散块/, "shape-fracture"],
  [/星图|中枢|辐射|hub/, "shape-hub"],
  [/节拍|卡点|beat/, "rhythm-beat"],
  [/蒙太奇|分屏|四宫|montage/, "rhythm-montage"],
  [/变速|快慢|speed ramp/, "rhythm-speed"],
  [/频闪|黑帧|strobe/, "rhythm-strobe"],
  [/人物|头像|人像|avatar/, "person-avatar"],
  [/对话|消息|聊天|chat|message/, "person-chat"],
  [/字标|品牌|logo|wordmark/, "brand-logo"],
  [/画框|边框|霓虹框|frame/, "brand-frame"],
  [/标注|圈重点|注释|annotate/, "annotate-mark"],
  [/纹理|底纹|条纹|背景|texture/, "background-texture"],
  [/海报|照片墙|合影|photo/, "background-photo"],
  [/玻璃|虚化|毛玻璃|glass/, "background-glass"],
  [/场景|舞台|scene/, "background-scene"],
  [/声纹|音频|audio|语音/, "media-audio"]
];

const categoryGlyphs: Readonly<Record<string, EffectGlyphKey>> = {
  标题: "type-assemble",
  强调: "type-highlight",
  卡片: "ui-card",
  标注: "annotate-mark",
  数据: "data-bar",
  布局: "ui-panel",
  场景: "background-scene",
  背景: "background-texture",
  展示: "ui-window",
  高级: "scene-3d"
};

export function effectGlyphKey(effect: CompositionDefinition): EffectGlyphKey {
  const byId = effectIdGlyphs[effect.id];
  if (byId) return byId;
  const card = shotcraftShot(effect.id)?.card;
  if (card) {
    const byCard = shotcraftCardGlyphs[card];
    if (byCard) return byCard;
  }
  for (const tag of effect.tags) {
    const byVocabulary = overlayVocabularyGlyphs[tag];
    if (byVocabulary) return byVocabulary;
  }
  const haystack = `${effect.name} ${effect.description} ${effect.tags.join(" ")}`.toLocaleLowerCase("zh-CN");
  for (const [pattern, glyph] of keywordGlyphs) {
    if (pattern.test(haystack)) return glyph;
  }
  return categoryGlyphs[effect.category] ?? "ui-window";
}
