// Generated by scripts/sync-motion-matching-catalog.mjs. Do not edit manually.
export const referenceMotionMatchingPolicy = {
  "densityPerMinute": {
    "min": 8,
    "max": 12
  },
  "newActionIntervalSeconds": {
    "min": 2,
    "max": 4
  },
  "typicalSegmentSeconds": {
    "min": 10,
    "max": 30
  },
  "openingHookDeadlineSeconds": 5,
  "maxConcurrentContentLayers": 2,
  "minContentEntryStaggerSeconds": 0.5
} as const;

export const referenceMotionMatchingCards = [
  {
    "id": "chapter-bar",
    "purposeGroup": "常驻层",
    "verticalPolicy": "still 不让",
    "purpose": "章节导航条,贴顶全宽全程在场",
    "triggerWhen": "每期一张,start=0 到视频结尾",
    "parameterGuide": "`chapters`(「章名 起始秒」`\\|`分隔)、`accent`、`showProgress`"
  },
  {
    "id": "pin-board",
    "purposeGroup": "常驻层",
    "verticalPolicy": "half 人下沉",
    "purpose": "要点钉板 · 讲过的要点逐条钉在角落,全程不消失",
    "triggerWhen": "一段里有 2-4 条短要点要「讲过也不撤」,钉在角落陪跑整段;比信息板轻,只放短句不放数据行",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`title`(章节标题(可空))、`subtitle`(强调副题(可空))、`items`(要点(/ 分隔,逐条落钉))、`stepMs`(每条落钉间隔(卡点用))、`accent`(强调色(副题))"
  },
  {
    "id": "caption-track",
    "purposeGroup": "常驻层",
    "verticalPolicy": "still 不让",
    "purpose": "双语字幕层,底部居中全程在场",
    "triggerWhen": "每期一张,start=0 到视频结尾",
    "parameterGuide": "`lines`(一行一条`起始\\|结束\\|中文\\|英文`,中文夹`*关键词*`)、`accent`、`showEn`"
  },
  {
    "id": "glass-pane",
    "purposeGroup": "常驻层",
    "verticalPolicy": "still 不让",
    "purpose": "玻璃底幕 · 一侧黑玻璃渐变垫底,亮视频上给特效区压出暗底",
    "triggerWhen": "底下的原片偏亮/偏花,特效区文字压不住时垫一层;**一段只垫一层,别叠**",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`layer`(叠放层级)、`side`(落位)、`width`(宽度)、`strength`(浓度)、`blur`(背景虚化)"
  },
  {
    "id": "frost-screen",
    "purposeGroup": "常驻层",
    "verticalPolicy": "still 不让",
    "purpose": "全屏毛玻璃 · 整块画面虚化+黑/白玻璃底,让开顶部进度条",
    "triggerWhen": "整段要把原片压成背景板(讲纯概念、念金句),自动让开顶部章节条",
    "parameterGuide": "`tone`(玻璃底色)、`blur`(虚化程度)、`alpha`(玻璃底浓度)、`topSafe`(顶部让开(章节条 48px))、`bottomSafe`(底部让开(字幕))"
  },
  {
    "id": "info-board",
    "purposeGroup": "证据实证",
    "verticalPolicy": "full 人缩小窗",
    "purpose": "累积信息板(论点板):一块板陪跑整个论点 15~30s,大标题/红框标签/数据条/大数字/引语/前后对比/红章 按卡点逐行点亮,讲过的行压暗",
    "triggerWhen": "一个论点有 3 条以上要点/数据要\"越讲越厚\"时,用这一张代替一堆快闪小卡;红章行放论点收尾",
    "parameterGuide": "`rows`(一行一条:`head\\|主行\\|强调行\\|EN`,`tag\\|文字`,`bar\\|名目\\|0-100\\|数值`,`kv\\|名目\\|大数字\\|小注`,`quote\\|引语\\|署名`,`shift\\|名目\\|之前\\|之后`,`stat\\|EN标签\\|中文\\|图标名`(**状态行**:带框 mono EN+中文+右侧⚠,\"STALLED 转圈慢\"式故障/状态列表),`formula\\|图标名\\|A = B → C`(**公式行**:因果链自动配色),`img\\|图或视频路径\\|标注`(**证据图行**:截图/视频占满板宽,空路径=占位),`count\\|前缀\\|数字\\|单位`(**滚动计数行**,行点亮时滚上去),`mult\\|名目\\|主值\\|×N`(**倍数徽章行**,红×N 量级差),`chip\\|文字\\|图标名`(**中性胶囊行**,产品/版本名),`note\\|mono小字`(**小注行**,来源/口径),`icons\\|图标或图路径逗号分隔\\|小注`(**横排logo行**),`spark\\|名目\\|up或down\\|幅度注`(**迷你趋势线行**,小曲线画出升绿降红),`ring\\|名目\\|百分比\\|数值文字`(**圆环占比行**,环注水),`dots\\|名目\\|总数\\|点亮数`(**点阵比例行**,\"10 个里 8 个\"点逐个亮),`strike\\|旧认知\\|真相`(**反转行**,旧划红线真相砸出,strike-flip 板内版),`check\\|文字\\|空或x`(**打勾行**,绿勾/红叉弹出,一项一行按卡点亮,checklist 板内版),`compare\\|强调项 数值\\|对照项 数值\\|名目`(**双条对比行**,彩条vs灰条,compare-split 板内版),`term\\|EN\\|术语\\|定义`(**术语行**,term-card 板内版),`stamp\\|中文\\|EN`)、`times`(每行点亮秒数,按 SRT 卡点)、`bg`(dark黑玻璃/**light白玻璃**/none,黑白按当期画面逐卡选)、`rowFx`(行强调方式:lit 点亮(默认)/zoom 稍微放大/both 点亮+放大)、`bgAlpha`(底板透明度 0.2-1,越小越透,默认 0.6)、`accent`、`position` `ent|头像图|名字|身份`(实体名牌行,人物/机构混排进脊柱) 新增行:`vs|左值|右值|名目`(比分,大绿小红) `line|标签 ✗/✓ 说明;标签 ✗/✓ 说明`(时间线,✗红✓绿)"
  },
  {
    "id": "dot-crowd",
    "purposeGroup": "证据实证",
    "verticalPolicy": "half 人下沉",
    "purpose": "点阵人群比:大数字铺成一片点阵逐个亮起(规模感),再压红条比例、黄字数量,巨型比率收尾",
    "triggerWhen": "\"人多机会少\"式供需悬殊:13.4万群演 vs 700-800 通告 → 167:1",
    "parameterGuide": "`title`(名目`\\|`大数字)、`dots`(点数)、`sub1`(红条:强调`\\|`小注`\\|`0-100)、`sub2`(黄字:名目`\\|`大数字`\\|`单位)、`ratio`(比率`\\|`小注,留空不要)、`times`(四段:点阵`\\|`红条`\\|`黄字`\\|`比率)、`accent`、`position`"
  },
  {
    "id": "stat-proof",
    "purposeGroup": "证据实证",
    "verticalPolicy": "half 人下沉",
    "purpose": "数字实证,巨号滚动计数",
    "triggerWhen": "里程碑/成绩/金额:\"三万粉达成\"",
    "parameterGuide": "`kicker`(EN等宽)、`kickerZh`、`value`、`prefix`/`suffix`、`footEn`/`footZh`、`countMs`(卡点)、`position`"
  },
  {
    "id": "proof-shot",
    "purposeGroup": "证据实证",
    "verticalPolicy": "half 人下沉",
    "purpose": "截图实证 + 认证章",
    "triggerWhen": "后台数据/评论/引用画面,用真素材背书",
    "parameterGuide": "`img1`-`img3`(多图按 `stepMs` 依次翻页,最后一张定格)、`tag`(默认 REAL·数据自查)、`caption`(来源归因)、`captionEn`、`marks`(**红笔标注**,一行一条「图序\\|line\\|左%\\|上%\\|宽%」或「图序\\|box\\|左%\\|上%\\|宽%\\|高%」,翻到该页才画——截图从\"贴上来\"变\"被讲解\")、`position` img 槽可填 `/demo/xxx.mp4` 视频片段(小窗循环播放,证据会动)"
  },
  {
    "id": "proof-wall",
    "purposeGroup": "证据实证",
    "verticalPolicy": "still 不让",
    "purpose": "截图墙 · 网友截图一张张弹出来,越堆越多,拼满半边屏",
    "triggerWhen": "口播说到「很多人夸/很多人复刻/反馈超预期」这类**社会证明**,手上有一叠截图想一次全亮出来:要的是「这么多人」的量感,不是看清某一张。只有 1-2 张、或需要红笔圈重点 → 用 `proof-shot`",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`side`(贴哪半边)、`img1`…`img10`(截图 1…10,**最多 10 张**,填几张就自动换几张的布局)、`times`(每张弹出秒(/ 分隔;留空 = 匀速))、`firstAt`(第一张晚多久弹)、`stepMs`(弹出间隔(times 填了就无效))、`width`(墙占屏宽)、`tilt`(歪斜幅度)、`fit`(截图怎么塞进格子:cover 填满 / contain 完整显示,**横竖混排的截图用 contain**)、`tag`(角标(空 = 不显示))、`countZh`(计数后缀(空 = 不显示 +N))、`safeBottom`(底部字幕安全区)、`bg`(暗底)、`accent`(强调色)、`scale`(整墙大小)、`offsetX`/`offsetY`(位置微调)"
  },
  {
    "id": "ghost-video",
    "purposeGroup": "证据实证",
    "verticalPolicy": "still 不让",
    "purpose": "幽灵参考视频 · 半透明+四边羽化融进画面,展示素材不压人脸",
    "triggerWhen": "提到某个参考素材/往期片段,想让它露个面又不抢戏、不压脸",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`src`(素材路径(视频/图))、`side`(落位)、`top`(距顶)、`w`(宽度)、`opacity`(透明度)、`feather`(边缘羽化)、`tilt`(3D 倾斜)"
  },
  {
    "id": "phone-shot",
    "purposeGroup": "证据实证",
    "verticalPolicy": "half 人下沉",
    "purpose": "手机壳证据:截图/视频装进手机+发光+分类标签",
    "triggerWhen": "评论/私信/聊天记录/自己往期视频,讲具体案例故事",
    "parameterGuide": "`tag`(分类标签如\"评论区·真实提问\")、`img1`-`img3`(循环翻页)、`videoSrc`、`stepMs`、`glow`、`position`"
  },
  {
    "id": "doc-scroll",
    "purposeGroup": "证据实证",
    "verticalPolicy": "half 人下沉",
    "purpose": "文档滚动:长截图在窗口里缓缓滚过+高亮条",
    "triggerWhen": "引用文章原文/协议/长文档(\"你的合同=你的原文\")",
    "parameterGuide": "`title`(来源归因)、`img1`(整页长截图)、`scrollMs`(≈卡片时长)、`highlight`、`position`"
  },
  {
    "id": "fact-stack",
    "purposeGroup": "证据实证",
    "verticalPolicy": "still 不让",
    "purpose": "累积数字胶囊:逐颗落地全程不消失",
    "triggerWhen": "故事里的数字(\"2名→¥1万→2周\"),讲到哪颗弹哪颗",
    "parameterGuide": "`items`(「大字 小注」`\\|`分隔)、`stepMs`(对齐报数时刻)、`position`(bottom-left 等)"
  },
  {
    "id": "win-lose",
    "purposeGroup": "证据实证",
    "verticalPolicy": "still 不让",
    "purpose": "胜负对比,层级即观点",
    "triggerWhen": "\"我选了A没选B\"的取舍",
    "parameterGuide": "`winName`/`winNote`/`winTag`、`loseName`/`loseNote`/`loseTag`、`position`"
  },
  {
    "id": "rule-card",
    "purposeGroup": "证据实证",
    "verticalPolicy": "still 不让",
    "purpose": "大绿勾主张 + 划掉的红禁区",
    "triggerWhen": "\"坚持X,绝不A/B/C\"的立场",
    "parameterGuide": "`text`(2-6字)、`subEn`、`bans`(`\\|`分隔)、`stepMs`(卡点)、`position`"
  },
  {
    "id": "bar-race",
    "purposeGroup": "证据实证",
    "verticalPolicy": "still 不让",
    "purpose": "条形赛跑,最大值自动高亮",
    "triggerWhen": "量级对比:\"1/周12% vs 75/天96%\"",
    "parameterGuide": "`kicker`/`kickerZh`、`rows`(「标签 数值」`\\|`分隔)、`unit`、`stepMs`(卡点)、`verdict`(结论盖章,条形跑完弹出)、`layout`(**h 横条 / v 竖柱**——数值顶在柱头、标签在底、最大柱自动绿,时间序列涨势用 v 气势足;非最大柱跟 accent,最高柱色用 topAccent 换,想要\"蓝柱+绿顶\"就 accent=blue)、`position`"
  },
  {
    "id": "photo-halo",
    "purposeGroup": "证据实证",
    "verticalPolicy": "still 不让",
    "purpose": "照片环绕:最多 6 张圆角照片**绕人物椭圆公转**(下近上远、近大远小)+轻微摆动",
    "triggerWhen": "一堆素材/案例/成果\"集体亮相\"的开场或总结时刻;人会被卡盖住 → 交付说明里提醒配剪映智能抠像(人叠回最上层)",
    "parameterGuide": "`img1`-`img6`(空槽不显示)、`stepMs`(逐张弹入)、`orbitSec`(公转一圈秒数,0=不转,默认36)、`bob`(摆动幅度,0=不摆)"
  },
  {
    "id": "stick-fall",
    "purposeGroup": "证据实证",
    "verticalPolicy": "still 不让",
    "purpose": "火柴人小剧场 · 28 个动作任意串成一段戏,配道具和场景(卡点)",
    "triggerWhen": "**任何「人在干什么、干到什么状态」的口播都能演**,不限于堆素材。听到「跑不动了 / 无语 / 躺平 / 求求了 / 一直在拍 / 扛着干 / 破防」这类带动作或情绪的说法就考虑它 —— 动作和口播说法的完整对照见下方「火柴人动作表」,照着编 `acts` 剧本,不要套固定那一出。要的是喜剧感和代入感;纯讲数字增长 → `number-beats` / `bar-race`",
    "parameterGuide": "`acts`(剧本:一行一拍「秒\\|动作[+道具]」)、`scene`(背景:素材堆/赛道/无)、`label`(背景标签)、`pileMax`(堆几块)、`theme`(底色)、`position`(落位)、`accent`(强调色)"
  },
  {
    "id": "metric-focus",
    "purposeGroup": "数据指标",
    "verticalPolicy": "half 人下沉",
    "purpose": "核心数字",
    "triggerWhen": "单个大数字:\"留存率92.4%\"",
    "parameterGuide": "`kicker`、`value`、`decimals`、`suffix`、`caption`、`accent`(默认blue)、`side`(left/right)"
  },
  {
    "id": "ring-metric",
    "purposeGroup": "数据指标",
    "verticalPolicy": "half 人下沉",
    "purpose": "指标环",
    "triggerWhen": "单个比例指标(圆环更醒目)",
    "parameterGuide": "`kicker`、`value`、`max`、`unit`、`label`、`position`(left/right/center)"
  },
  {
    "id": "odometer",
    "purposeGroup": "数据指标",
    "verticalPolicy": "still 不让",
    "purpose": "翻牌计数器",
    "triggerWhen": "单个整数的里程表滚轮(比 metric-focus 更机械感)",
    "parameterGuide": "`kicker`、`value`(整数)、`unit`、`label`、`position`"
  },
  {
    "id": "number-beats",
    "purposeGroup": "数据指标",
    "verticalPolicy": "still 不让",
    "purpose": "大数字分点",
    "triggerWhen": "\"第一/第二/第三\"分点讲述",
    "parameterGuide": "`points`(`标题,一句话`用`\\|`分隔)、`holdMs`(每点停留,对齐讲述节奏)、`position`(left/right/center)"
  },
  {
    "id": "rank-bars",
    "purposeGroup": "数据指标",
    "verticalPolicy": "half 人下沉",
    "purpose": "数据排名条",
    "triggerWhen": "多项数据对比排名:\"A 42%、B 21%\"",
    "parameterGuide": "`title`、`rows`(`名称,数值`用`\\|`分隔)、`suffix`、`position`(left/right)"
  },
  {
    "id": "scale-swap",
    "purposeGroup": "数据指标",
    "verticalPolicy": "half 人下沉",
    "purpose": "尺子换对了 · 同一数字两把刻度,假进度条现形",
    "triggerWhen": "「换把尺子就现原形」:同一个数字在旧口径下好看,换新口径后露馅",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`title`(标题(\\\\n 分行,*星号*=强调红))、`labelA`(条A名目(旧刻度))、`pctA`(条A读数(%))、`tagA`(条A旁注)、`markPct`(真实窗口位置(%))、`markNote`(虚线标记注释)、`labelB`(条B名目(新刻度))、`valB`(条B大数字)、`warnB`(条B警告语)、`foot`(底注)、`times`(5 拍秒数(标题/条A/标记/条B/底注))、`bgAlpha`(底板透明度(越小越透))、`accent`(强调色(标题红/深红条))"
  },
  {
    "id": "stack-share",
    "purposeGroup": "数据指标",
    "verticalPolicy": "half 人下沉",
    "purpose": "占比拆解 · 一根堆叠条看清钱花哪了",
    "triggerWhen": "一个总量拆成几块占比:钱花哪了、时间花哪了",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`kicker`(眉题(EN 等宽))、`title`(标题(\\\\n 分行,*星号*=强调色))、`segs`(分段(占比 名称,/ 分隔))、`bracketN`(括号圈前几段)、`bracketText`(括号文字)、`caption`(条下说明)、`note`(绿框批注(*星号*=绿色加粗))、`times`(5 拍秒数(标题/条/括号/图例/批注))、`accent`(强调色(标题/分段条))"
  },
  {
    "id": "column-stack",
    "purposeGroup": "数据指标",
    "verticalPolicy": "full 人缩小窗",
    "purpose": "逐轮堆叠柱 · 底层越垫越厚,新增只有薄薄一层",
    "triggerWhen": "讲复利/存量积累:每轮新增只有薄薄一层,但底子越垫越厚",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`kicker`(眉题(EN 等宽))、`title`(标题(\\\\n 分行,*星号*=强调色))、`rounds`(柱子根数)、`pow`(增长曲线(1=线性,大=后程发力))、`legendA`(图例·薄盖层(绿))、`legendB`(图例·厚底层(跟强调色))、`ticks`(横轴刻度(/ 分隔均匀铺开))、`foot`(底注)、`times`(4 拍秒数(标题/柱阵/图例/底注))、`accent`(强调色(标题/柱身))"
  },
  {
    "id": "stair-bars",
    "purposeGroup": "数据指标",
    "verticalPolicy": "half 人下沉",
    "purpose": "分档对比柱 · 绿到红逐级恶化,同指标不同档",
    "triggerWhen": "同一个指标在不同档位下逐级恶化或改善(3-5 档,绿→红)",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`kicker`(眉题(EN 等宽))、`title`(标题(\\\\n 分行,*星号*=强调色))、`vals`(柱值(数字,/ 分隔))、`valTexts`(柱顶数值文案(/ 分隔))、`labels`(档位标签(/ 分隔))、`colors`(柱色(/ 分隔,可用 var(--hud-*) 令牌))、`grid`(网格线数值(/ 分隔))、`gridUnit`(网格线单位)、`caption`(柱下说明)、`foot`(底注(*星号*=加粗))、`times`(4 拍秒数(标题/柱/说明/底注))、`accent`(强调色(眉题/标题))"
  },
  {
    "id": "multiply-grid",
    "purposeGroup": "数据指标",
    "verticalPolicy": "half 人下沉",
    "purpose": "乘法成本 · 方块阵 列×行,两个乘数是相乘不是相加",
    "triggerWhen": "强调「是相乘不是相加」的量级爆炸:N 个人 × M 次",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`kicker`(眉题(EN 等宽))、`title`(标题(\\\\n 分行,*星号*=强调色))、`gridCols`(方块列数)、`gridRows`(方块行数)、`result`(结果行(强调色))、`factor1`(乘数一)、`factor2`(乘数二)、`gridCaption`(左卡小字)、`statVal`(右卡大数字)、`statUnit`(右卡角标)、`statText`(右卡正文(*星号*=加粗))、`times`(5 拍秒数(标题/方块/结果/大数/正文))、`accent`(强调色(方块/大数字))"
  },
  {
    "id": "growth-curve",
    "purposeGroup": "数据指标",
    "verticalPolicy": "half 人下沉",
    "purpose": "增长曲线:平滑曲线动画画出+渐变面积,峰值滚动计数",
    "triggerWhen": "\"越攒越多/一路上涨\"的复利叙事(粉丝数、资产库存、收入)",
    "parameterGuide": "`kicker`/`kickerZh`、`points`(「标签 数值」`\\|`分隔)、`unit`、`drawMs`(画完时长,卡点)、`caption`(数据口径)、`position`"
  },
  {
    "id": "diverge-lines",
    "purposeGroup": "数据指标",
    "verticalPolicy": "still 不让",
    "purpose": "双线分叉图:绿线升红线降,同点出发反向走,端点亮起后标签带↗↘箭头浮现",
    "triggerWhen": "两个量此消彼长/矛盾失衡的结论时刻(\"用户量↑ 算力供给↓\")",
    "parameterGuide": "`aLabel`/`bLabel`(两线标签)、`aColor`/`bColor`(两线颜色,默认绿/红,可换主题色)、`mode`(**split 一升一降(默认)/ gap 差距模式**:同起点都在涨、A 发光指数上扬带里程碑亮点、B 灰线平走,终点红虚线把差距竖着量出——\"拉开差距/一快一慢\"的语义用 gap)、`gapLabel`(gap 模式差距标注,如 \"效率差距 Δ\")、`drawMs`(画出时长,卡点)、`kicker`/`kickerZh`(可空)、`bg`(dark黑玻璃/none)、`position`"
  },
  {
    "id": "drop-arrow",
    "purposeGroup": "数据指标",
    "verticalPolicy": "half 人下沉",
    "purpose": "降幅大箭头 · 前值→俯冲箭头→后值,巨号降幅百分比砸出",
    "triggerWhen": "一个数字大幅下降,要砸出降幅百分比(上涨用 growth-curve)",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`kicker`(EN 眉题(可空))、`title`(标题(\\\\n 分行,*词*强调))、`fromVal`(前值)、`fromLabel`(前值小注)、`toVal`(后值)、`toLabel`(后值小注)、`pct`(降幅大字(如 −88%))、`pctNote`(降幅小注)、`foot`(底注(可空,*词*加粗))、`times`(4 拍点亮秒数:标题/前值/箭头+后值/降幅)、`accent`(强调色)"
  },
  {
    "id": "compare-split",
    "purposeGroup": "对比取舍",
    "verticalPolicy": "still 不让",
    "purpose": "双条对比",
    "triggerWhen": "两个数值前后对比(A=强调项彩色,B=对照项灰)",
    "parameterGuide": "`title`、`aLabel`/`aValue`(强调)、`bLabel`/`bValue`(对照)、`suffix`、`side`"
  },
  {
    "id": "cost-cut",
    "purposeGroup": "对比取舍",
    "verticalPolicy": "half 人下沉",
    "purpose": "成本压缩条 · 两条对比压到最短 + 结论巨字",
    "triggerWhen": "新做法把耗时/成本压到极短:「原来三天,现在三分钟」",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`kicker`(眉题(EN))、`kickerZh`(眉题中文)、`oldZh`(旧做法·中文)、`oldEn`(旧做法·EN)、`oldPct`(旧做法·条长)、`oldNote`(旧做法·条尾小注)、`newZh`(新做法·中文)、`newEn`(新做法·EN)、`newPct`(新做法·条长)、`newNote`(新做法·条尾小注)、`newIcon`(新做法·图标(矢量名))、`punch`(结论巨字)、`punchEn`(结论 EN 小字)、`oldAt`(旧条画出(s))、`newAt`(新条画出(s))、`punchAt`(巨字砸下(s))、`arrow`(两条之间的压缩箭头)、`accent`(强调色)"
  },
  {
    "id": "versus-card",
    "purposeGroup": "对比取舍",
    "verticalPolicy": "still 不让",
    "purpose": "VS 对比卡",
    "triggerWhen": "二选一对撞:\"主动 vs 被动\"",
    "parameterGuide": "`aKicker`/`aTitle`/`aSub`、`bKicker`/`bTitle`/`bSub`、`winner`(a/b/none)"
  },
  {
    "id": "compare-bars",
    "purposeGroup": "对比取舍",
    "verticalPolicy": "half 人下沉",
    "purpose": "派与不派 · 反例/正例徽标卡 + 一长一短量级条",
    "triggerWhen": "「这么做 vs 那么做」:两边各一张说明卡 + 一长一短的量级条",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`kicker`(眉题(EN 等宽))、`title`(标题(\\\\n 分行,*星号*=强调色))、`cardBad`(反例卡(徽标~标题~正文))、`cardGood`(正例卡(徽标~标题~正文))、`barALabel`(条A名目(红长条))、`barAVal`(条A数值)、`barAPct`(条A长度(%))、`barBLabel`(条B名目(绿短条))、`barBVal`(条B数值)、`barBPct`(条B长度(%))、`barNote`(条B结论(绿))、`times`(5 拍秒数(标题/反例/正例/条A/条B))、`accent`(强调色(眉题/标题))"
  },
  {
    "id": "strike-flip",
    "purposeGroup": "对比取舍",
    "verticalPolicy": "half 人下沉",
    "purpose": "反转打脸卡",
    "triggerWhen": "\"X≠Y\"认知反转;\"不是A、也不是B——而是C\"的多重否定(最多划掉 3 条)",
    "parameterGuide": "`aText`/`aText2`/`aText3`(被划掉的常识,2/3 可空)、`bText`(砸出的真相)、`strikeAtMs`(第 1 条划线时刻)、`strikeStepMs`(逐条划线间隔,按 SRT 推算)、`position`"
  },
  {
    "id": "icon-veto",
    "purposeGroup": "对比取舍",
    "verticalPolicy": "still 不让",
    "purpose": "图标打叉:图标徽章+概念文字先立起来,红✗划过整体(末班车?✗式图形化否定)",
    "triggerWhen": "破除迷思/\"你以为的X\"时刻——比划文字高级,一眼懂不用读;常配换景段浮在 b-roll 上",
    "parameterGuide": "`icon`(矢量图标名:train/rocket/clock…)、`text`(概念文字)、`vetoAt`(打叉时刻=否定句开口那一刻,卡点)、`accent`(徽章色,✗固定红)、`position`"
  },
  {
    "id": "quote-lockup",
    "purposeGroup": "金句观点",
    "verticalPolicy": "half 人下沉",
    "purpose": "金句定格卡",
    "triggerWhen": "多行金句逐行揭示(毛玻璃卡)",
    "parameterGuide": "`quote`(`\\|`分行)、`author`、`accent`(默认pink)、`side`(left/right)"
  },
  {
    "id": "quote-cite",
    "purposeGroup": "金句观点",
    "verticalPolicy": "half 人下沉",
    "purpose": "引用卡",
    "triggerWhen": "引用他人的话/观点(带头像来源);**quote 留空 = 纯人物介绍模式**(只剩大头像+名字+身份,介绍作者/嘉宾时用)",
    "parameterGuide": "`quote`(空=人物介绍)、`img1`(真头像图,Twitter 头像等,列进素材清单)、`avatar`(没图时的字/emoji 占位)、`author`、`source`、`media`(none/image/video)、`position`(left/right)"
  },
  {
    "id": "punch-pill",
    "purposeGroup": "金句观点",
    "verticalPolicy": "still 不让",
    "purpose": "金句药丸",
    "triggerWhen": "短金句/设问定格:\"你怎么选?\"",
    "parameterGuide": "`text`、`position`(bottom/top-left/top-right)"
  },
  {
    "id": "formula-pill",
    "purposeGroup": "金句观点",
    "verticalPolicy": "still 不让",
    "purpose": "公式药丸:图标 + A = B → C 一行讲完一个机制,自动配色(首节白/中间跟点缀色/→后结果绿)",
    "triggerWhen": "图表/证据块下方的机制脚注(\"邀请好友 = 额度重置 → 需求被点燃\")",
    "parameterGuide": "`icon`(矢量图标名,空=无)、`text`(用 = 和 → 分节)、`accent`(中间节颜色)、`resAccent`(结果节颜色,默认绿)、`position`"
  },
  {
    "id": "kinetic-words",
    "purposeGroup": "金句观点",
    "verticalPolicy": "half 人下沉",
    "purpose": "逐词大字钩子",
    "triggerWhen": "开头设问/情绪钩子:\"你是不是也这样?\"",
    "parameterGuide": "`chunks`(词块`\\|`分隔,`*关键词*`高亮)、`holdMs`(默认750)、`position`(center/top/bottom)"
  },
  {
    "id": "karaoke-line",
    "purposeGroup": "金句观点",
    "verticalPolicy": "still 不让",
    "purpose": "跟读高亮句",
    "triggerWhen": "需要观众逐字跟上的关键旁白句",
    "parameterGuide": "`words`(词块`\\|`分隔按语速)、`wordMs`(默认420)、`position`(bottom/top/center)"
  },
  {
    "id": "word-spin",
    "purposeGroup": "金句观点",
    "verticalPolicy": "half 人下沉",
    "purpose": "词槽轮换",
    "triggerWhen": "一句式列举多种能力:\"它能帮你[写代码→做PPT→…]\"",
    "parameterGuide": "`prefix`、`words`(`\\|`分隔)、`suffix`、`spinMs`、`position`"
  },
  {
    "id": "clip-flow",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "still 不让",
    "purpose": "素材流水线 · 传送带进机器/拖拽入库/扫描选中,全程连续动画",
    "triggerWhen": "讲**物料怎么流动**:素材进来、被处理、出去。三种模式:`conveyor` 素材进机器出成片、`drop` 拖进库归档、`pick` 从一堆里扫描挑中。讲抽象的步骤链条(不涉及物料) → `flow-chart` / `stepper-flow`",
    "parameterGuide": "`mode`(模式)、`items`(素材块(emoji 或「emoji 标签」,/ 分隔))、`label`(机器 / 落袋区 / 素材库名)、`inLabel`(入料小标(conveyor))、`outLabel`(产出小标(conveyor/pick))、`times`(卡点秒(drop=每块落袋 / pick=扫描增强/飞出))、`periodSec`(节奏周期)、`picks`(选中的格序号(pick,/ 分隔))、`zoneIcon`(落袋区 App 图标(drop,图路径,空=虚线袋))、`hubX`(图标中枢距离(feed 版,越小越近))、`theme`(底色)、`position`(落位)、`accent`(强调色)"
  },
  {
    "id": "step-timeline",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "half 人下沉",
    "purpose": "竖版章节卡",
    "triggerWhen": "本期章节/教程大纲",
    "parameterGuide": "`title`(`*关键词*`)、`steps`(`\\|`分隔)、`revealed`(讲到第几章)、`position`(left/right)"
  },
  {
    "id": "chat-volley",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "half 人下沉",
    "purpose": "对话往返 · 气泡在两端头徽间穿梭,落成记录,绿戳收尾(卡点)",
    "triggerWhen": "演示「来回沟通了几轮才成」的过程——重点是往返和最后达成,不是具体说了什么。只引用其中一句话 → `quote-cite`",
    "parameterGuide": "`leftLabel`(左端头徽(文字))、`leftImg`(左端头像图(填了就用图))、`rightLabel`(右端头徽(文字))、`rightImg`(右端图标(填了就用图))、`stampIcon`(收尾戳小图标(空=用✓))、`msgs`(消息(一行一条:L/文字 左发出,R/文字 右发回))、`times`(卡点秒:每条发出时刻,末尾可多给一位=收尾戳)、`counter`(顶部计数标签(空=不显示))、`stampText`(收尾戳文字(绿,空=不显示))、`theme`(底色)、`position`(落位)、`accent`(强调色)"
  },
  {
    "id": "checklist",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "half 人下沉",
    "purpose": "步骤打勾",
    "triggerWhen": "流程逐项完成",
    "parameterGuide": "`title`、`items`(`\\|`分隔)、`checked`(已完成数)、`stepMs`(每项间隔,按SRT算)、`position`(left/right)"
  },
  {
    "id": "action-band",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "half 人下沉",
    "purpose": "动作卡组 · 编号白卡×N + 红绿灯分级色带",
    "triggerWhen": "给出 2-4 条可执行动作,并按风险/优先级分档(红黄绿色带)",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`kicker`(眉题(EN 等宽))、`title`(标题(\\\\n 分行,*星号*=强调色))、`badge`(徽标前缀(自动编号))、`cards`(动作卡(标题~正文,/ 分隔,*星号*=加粗))、`band`(色带(文字 宽度 颜色,/ 分隔,可用 var(--hud-*)))、`bandCaption`(色带说明)、`foot`(底注(*星号*=加粗))、`times`(5 拍秒数(标题/卡组/色带/说明/底注))、`accent`(强调色(眉题/徽标))"
  },
  {
    "id": "stepper-flow",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "still 不让",
    "purpose": "步骤指示",
    "triggerWhen": "流程自动逐步推进(编号圆点+注水线)",
    "parameterGuide": "`steps`(`\\|`分隔)、`stepMs`、`loop`、`position`(center/top/bottom)"
  },
  {
    "id": "studio-build",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "half 人下沉",
    "purpose": "基建三拍 · 动效库铺开→收进编辑台→以后每条几分钟",
    "triggerWhen": "讲「先把底子搭好,以后每次都快」的一次性投入叙事",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`kicker`(眉题(EN · 中文))、`libEn`(① EN 标签)、`libZh`(① 中文说明)、`deckEn`(② EN 标签)、`deckZh`(② 中文说明)、`payEn`(③ EN 标签)、`payZh`(③ 中文(药丸))、`chips`(库里铺几张小卡)、`chipStepMs`(小卡逐张间隔)、`libAt`(① 第一张小卡出现秒(卡点))、`deckAt`(② 编辑台出现秒(卡点))、`payAt`(③ 收益出现秒(卡点))、`accent`(强调色)"
  },
  {
    "id": "replicate-loop",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "half 人下沉",
    "purpose": "复刻入库 · 看到→扔给大模型→复刻出来,飞进素材库,库亮一格 +1",
    "triggerWhen": "讲「看到好的 → 复刻 → 存进自己的库」的积累闭环",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`kicker`(眉题(EN · 中文))、`stops`(传送带三站(中文/图标名,一行一站))、`stopsAt`(每站点亮秒(/ 分隔,对着台词填))、`libZh`(库标题(中文))、`libEn`(库标题(EN))、`cells`(库的格子总数)、`filled`(起手已有几格(= 现在的库))、`intoAt`(飞进库的秒(库 +1 就在这一刻))、`note`(底部小注(可空))、`noteAt`(小注出现秒)、`accent`(强调色)"
  },
  {
    "id": "timeline-h",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "still 不让",
    "purpose": "横版时间线",
    "triggerWhen": "时间顺序事件:\"6/16 A→6/17 B→6/18 C\"",
    "parameterGuide": "`kicker`、`stops`(`日期,标题,副标`用`\\|`分隔)、`position`(top/bottom)"
  },
  {
    "id": "flow-chart",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "full 人缩小窗",
    "purpose": "自绘流程图",
    "triggerWhen": "流程链条:\"提需求→规划→执行→验证\"",
    "parameterGuide": "`title`、`nodes`(`\\|`分隔)、`stepMs`(每节点间隔,按SRT算)、`position`(left/right/center)"
  },
  {
    "id": "converge",
    "purposeGroup": "步骤流程",
    "verticalPolicy": "half 人下沉",
    "purpose": "汇聚结尾",
    "triggerWhen": "仅结尾:能力词飞向中心+金句。`core`、`nodes`(`\\|`)、`line`(`*关键词*`)",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`core`(中心)、`nodes`(汇聚的词(用 / 分隔))、`line`(收尾金句(*关键词* 高亮))、`accent`(强调色)"
  },
  {
    "id": "section-head",
    "purposeGroup": "信息结构",
    "verticalPolicy": "still 不让",
    "purpose": "段头三件套:竖色条+mono EN 标签+中文标题,段落常驻;`num` 填编号变章头大字(01 TOKEN COST 式);`size=s` 变**块级小标题**",
    "triggerWhen": "**每段一张**(start=段首,end=段尾,dimAt=下段开始;EN 标签=段意英译全大写);**每个证据块上方再钉一张 size=s 的**(start=块首,end=块尾)——原片人物和图表之间从不空,靠的就是块级标题",
    "parameterGuide": "`num`(空=段头/01=章头)、`en`(mono 英文标签)、`zh`(中文标题,`*重点词*`换色)、`sub`(论点行,可空)、`subAt`(论点行出现秒,卡点)、`src`(来源行,可空:SOURCE·出处·日期)、`size`(l 段头/s 块级标题)、`accent`(=段落语义色)、`position`(top-left 默认)"
  },
  {
    "id": "icon-swarm",
    "purposeGroup": "信息结构",
    "verticalPolicy": "still 不让",
    "purpose": "图标群 · 无底板 icon 词条分列点亮",
    "triggerWhen": "并列列举 4-8 个东西,但画面已经很满,不想再加底板",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`head`(大标题(中文))、`headEn`(标题 EN 灰字)、`items`(词条(一行一条:文字/图标名))、`startAt`(起始时刻(s))、`stepMs`(逐条间隔)、`layout`(排布)、`foot`(底部结论行)、`accent`(强调色)"
  },
  {
    "id": "stroke-title",
    "purposeGroup": "信息结构",
    "verticalPolicy": "still 不让",
    "purpose": "综艺花字 · 粗字黑描边大标题,前缀小标签+多行逐行砸出",
    "triggerWhen": "吐槽/搞笑/用力强调的大标题,要闹、要抢眼",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`tag`(前缀小标签(可空))、`text`(标题(/ 换行,*词* 强调色))、`fill`(主填色)、`accent`(强调色(*词*))、`size`(字号)、`stepMs`(每行间隔(卡点用))"
  },
  {
    "id": "duo-title",
    "purposeGroup": "信息结构",
    "verticalPolicy": "half 人下沉",
    "purpose": "双色块标题 · EN小标+两行色块大标题(黑底彩字/彩底黑字),一卡一对色",
    "triggerWhen": "段落大标题,内容是两行对仗结构(EN 小标 + 两行色块)",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`mode`(版式)、`en`(EN 小标(全大写))、`line1`(第一行(*词* 上 A 色))、`line2`(第二行(*词* 上 B 色))、`accentA`(A 色(第一行/短横))、`accentB`(B 色(第二行/下划线))、`grad`(第二行渐变色(A→B))、`chip1Bg`(第一块底色)、`chipShape`(色块形状)、`chipDeco`(色块外围虚线框)、`note`(小注(可空))、`noteAt`(小注出现秒)"
  },
  {
    "id": "chip-cluster",
    "purposeGroup": "信息结构",
    "verticalPolicy": "still 不让",
    "purpose": "发光圆徽组",
    "triggerWhen": "并列几个类别/场景:\"支付、高考、政务\"(透明发光圆环+强调色矢量线稿图标)",
    "parameterGuide": "`title`、`chips`(`图标,文字`用`\\|`分隔)、`stepMs`(每个间隔,按SRT算)、`position`(left/right)"
  },
  {
    "id": "glow-badges",
    "purposeGroup": "信息结构",
    "verticalPolicy": "half 人下沉",
    "purpose": "发光圆徽版式",
    "triggerWhen": "一个概念的完整版式讲解:EN 眉题(竖杠)+ 大标行(EN前缀+大中文+淡EN)+ 2-4 个发光圆徽逐个点亮(标签在圆上、名字小注在下)——\"MAP=Prompt/Skill/上下文\"这类\"一题多点\"结构",
    "parameterGuide": "`kicker`、`bg`(dark黑玻璃/light白玻璃底板,默认dark)、`tPre`/`tZh`/`tEn`、`badges`(`标签,图标,名字,小注`用`\\|`分隔)、`badgesAt`(第一个圆徽秒数,按 SRT 卡点)、`stepMs`、`position`"
  },
  {
    "id": "outline-tree",
    "purposeGroup": "信息结构",
    "verticalPolicy": "still 不让",
    "purpose": "结构树",
    "triggerWhen": "总-分结构:\"为什么?因为A、B、C\"",
    "parameterGuide": "`root`(父级)、`kids`(`\\|`分隔,`*关键词*`)、`stepMs`、`position`(left/right)"
  },
  {
    "id": "ecosystem-hub",
    "purposeGroup": "信息结构",
    "verticalPolicy": "full 人缩小窗",
    "purpose": "生态连接图",
    "triggerWhen": "中心连接多个外部工具/能力",
    "parameterGuide": "`hub`(中心名)、`icons`(`图标,名称`用`\\|`分隔)、`position`(center/left/right)"
  },
  {
    "id": "magic-bento",
    "purposeGroup": "信息结构",
    "verticalPolicy": "half 人下沉",
    "purpose": "便当格卡片墙",
    "triggerWhen": "功能全景一览(第1格加大,高亮巡游)",
    "parameterGuide": "`cells`(`标签,标题,描述`用`\\|`分隔)、`spotMs`、`position`"
  },
  {
    "id": "quad-map",
    "purposeGroup": "信息结构",
    "verticalPolicy": "half 人下沉",
    "purpose": "四象限认知图",
    "triggerWhen": "2×2 框架讲解(认知象限/优先级矩阵):黑玻璃外框 + 纸面白卡四宫格按卡点依次\"描边画出\",末格自动黑底反白;**讲解运镜**:填 `dockTimes`+`notes` 后,每格开讲时整图自动缩左、右侧黑玻璃框逐条弹讲解,下一格开画自动回中",
    "parameterGuide": "`cells`(textarea,一行一格`EN标题\\|EN斜体小注\\|中文名\\|中文一句话`)、`times`(每格开画秒数距卡片start,`\\|`分隔,**必须按 SRT 卡点填,支持不均匀间隔**)、`dockTimes`(每格缩左开讲秒数,`\\|`分隔,空=不运镜)、`notes`(讲解条目,一行一格、格内`\\|`分隔)、`noteStepMs`、`accent`(瞳孔/问号点缀色)、`position`(center/left/right)。讲四象限的整段只用这一张,不再叠小卡"
  },
  {
    "id": "map-territory",
    "purposeGroup": "信息结构",
    "verticalPolicy": "half 人下沉",
    "purpose": "地图与疆域",
    "triggerWhen": "两个概念对照讲解(比喻/模型 vs 现实):每侧\"标题横杠→条目逐条弹入→图像画出\"三段式,左侧虚线直线、右侧蜿蜒实线绕障碍,橙色 your unknowns 箭头点题,末幕两线之间空隙填橙呼吸(gap=未知点,纯图形);**标题/条目参数全留空 = 纯图案模式**(只剩两图+居中箭头,文字交给 glow-badges 等卡呈现)",
    "parameterGuide": "`times`(6 时刻`图题\\|图条目\\|域题\\|域条目\\|箭头\\|gap填色`,按 SRT 卡点)、`itemStepMs`、`mapEn`/`mapZh`/`mapItems`(图标,文字`\\|`分隔)、`terrEn`/`terrZh`/`terrItems`、`gapZh`、`position`"
  },
  {
    "id": "card-swap",
    "purposeGroup": "信息结构",
    "verticalPolicy": "half 人下沉",
    "purpose": "卡片轮换",
    "triggerWhen": "几个功能/要点堆叠轮流到前台",
    "parameterGuide": "`cards`(`标签,标题,描述`用`\\|`分隔)、`swapMs`、`position`"
  },
  {
    "id": "term-card",
    "purposeGroup": "教程标注",
    "verticalPolicy": "half 人下沉",
    "purpose": "术语解释卡",
    "triggerWhen": "出现术语要解释:Plan模式、MVP…",
    "parameterGuide": "`en`(英文)、`term`、`def`(一句话定义)、`position`(left/right)"
  },
  {
    "id": "ui-callout",
    "purposeGroup": "教程标注",
    "verticalPolicy": "still 不让",
    "purpose": "界面标注",
    "triggerWhen": "讲解界面某区域:\"项目入口在这里\"",
    "parameterGuide": "`label`、`ringW`/`ringH`(圈大小)、`side`、`offsetX`/`offsetY`(挪到目标位置)"
  },
  {
    "id": "icon-pop",
    "purposeGroup": "教程标注",
    "verticalPolicy": "still 不让",
    "purpose": "App 图标弹出:大圆角图标在人物头旁\"啵\"地弹出+轻漂",
    "triggerWhen": "口播提到某个 App/产品名的瞬间(2-5s);图留空交付时列进素材清单",
    "parameterGuide": "`img1`(方形图标图)、`position`(left/right 头旁)、`size`、`bob`(漂浮幅度)"
  },
  {
    "id": "marker-highlight",
    "purposeGroup": "教程标注",
    "verticalPolicy": "still 不让",
    "purpose": "关键词圈注",
    "triggerWhen": "一句话里划重点(马克笔/下划线)",
    "parameterGuide": "`text`(`*关键词*`圈注,`\\|` 手动换行)、`style`(marker/underline)、`position`(top/bottom/left/right)"
  },
  {
    "id": "steer-hint",
    "purposeGroup": "教程标注",
    "verticalPolicy": "half 人下沉",
    "purpose": "引导提示卡",
    "triggerWhen": "操作提示/功能要点(带标题条+✓要点)",
    "parameterGuide": "`head`(标题条)、`lead`、`points`(`\\|`分隔)、`position`(left/right)"
  },
  {
    "id": "pain-points",
    "purposeGroup": "教程标注",
    "verticalPolicy": "half 人下沉",
    "purpose": "痛点清单卡",
    "triggerWhen": "逐条罗列问题+扎心后果",
    "parameterGuide": "`kicker`(设问)、`pains`(`\\|`分隔)、`result`(后果)、`stepMs`(每条间隔,按SRT算)、`mark`/`resAccent`(alert/lav/pink)、`position`(left/right)"
  },
  {
    "id": "blur-text",
    "purposeGroup": "文字进场",
    "verticalPolicy": "still 不让",
    "purpose": "模糊浮现",
    "triggerWhen": "情绪/走心句,词块从虚焦中浮现",
    "parameterGuide": "`text`(`\\|`分隔,`*关键词*`可夹在句中)、`staggerMs`、`position`(center/top/bottom)"
  },
  {
    "id": "decrypt-text",
    "purposeGroup": "文字进场",
    "verticalPolicy": "still 不让",
    "purpose": "解密文字",
    "triggerWhen": "科技感揭晓:乱码逐字解密",
    "parameterGuide": "`kicker`、`text`(`*关键词*`)、`lockMs`、`position`"
  },
  {
    "id": "true-focus",
    "purposeGroup": "文字进场",
    "verticalPolicy": "still 不让",
    "purpose": "焦点扫词",
    "triggerWhen": "逐词咀嚼强调(对焦框跳词,其余虚化)",
    "parameterGuide": "`words`(`\\|`分隔)、`focusMs`、`loop`、`position`(center/top/bottom)"
  },
  {
    "id": "char-assemble",
    "purposeGroup": "文字进场",
    "verticalPolicy": "still 不让",
    "purpose": "字符聚拢",
    "triggerWhen": "单个重磅关键词出场:\"不可替代\"",
    "parameterGuide": "`lead`(引导小字)、`word`(聚拢词,2-6字)、`position`"
  },
  {
    "id": "type-shift",
    "purposeGroup": "文字进场",
    "verticalPolicy": "still 不让",
    "purpose": "排版流",
    "triggerWhen": "结尾升华/多行金句",
    "parameterGuide": "`lines`(`\\|`分隔;`*`开头=大标,`—`开头=小字)、`shiftAtMs`、`position`"
  },
  {
    "id": "word-flank",
    "purposeGroup": "文字进场",
    "verticalPolicy": "still 不让",
    "purpose": "巨字夹脸:巨型综艺黄大字一左一右\"砸\"在人物两侧,果冻弹入+轻微歪斜",
    "triggerWhen": "综艺感点名关键词(字\\|幕、免\\|费):比 char-assemble 更闹,搞笑/吐槽/强调时刻;字会压人 → 提醒配剪映智能抠像",
    "parameterGuide": "`words`(`\\|`分隔 1-4 块,落位 左→右→左下→右下)、`tone`(gold 综艺黄/accent 跟点缀色)、`stepMs`(逐块砸入)、`accent`"
  },
  {
    "id": "entity-chips",
    "purposeGroup": "人物锚定",
    "verticalPolicy": "still 不让",
    "purpose": "实体名牌:白牌(机构)+黑牌(人物·头衔)依次滑入后常驻,可带侧注(股票代码/身份)",
    "triggerWhen": "讲到具体的人/公司/产品时钉一排名牌锚定,整段讨论期间不撤,观众随时知道\"在说谁\";常配 `ambient-wash` 同段长驻留",
    "parameterGuide": "`chips`(一行一块:`light/dark\\|名称\\|身份或EN`,最多3块)、`note`(侧注 上行`\\|`下行)、`stepMs`、`accent`(黑牌身份行颜色)、`position`"
  },
  {
    "id": "hand-lift",
    "purposeGroup": "人物锚定",
    "verticalPolicy": "still 不让",
    "purpose": "手托展示 · 左右手各托起一个图标+名字",
    "triggerWhen": "两个东西并列端出来:「A 和 B」「这个工具 + 那个工具」",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`leftIcon`(左·图标(矢量名或 /logos/x.svg))、`leftName`(左·名字)、`leftNote`(左·小注)、`leftAt`(左·托起时刻(s))、`rightIcon`(右·图标(矢量名或 /logos/x.svg))、`rightName`(右·名字)、`rightNote`(右·小注)、`rightAt`(右·托起时刻(s))、`swap`(交换左右两块)、`leftX`(左·横向(px))、`leftY`(左·纵向(px))、`rightX`(右·横向(px))、`rightY`(右·纵向(px))、`glow`(掌心光晕)、`float`(悬浮幅度(px))、`accent`(强调色)"
  },
  {
    "id": "punch-zoom",
    "purposeGroup": "人物锚定",
    "verticalPolicy": "still 不让",
    "purpose": "镜头推近:金句时刻快推定住(camSrc 烤进导出)",
    "triggerWhen": "金句/反转/爆点开口那一刻(1.5-3s)",
    "parameterGuide": "`amount`(1.05-1.35)、`focus`(center/left/right)、`pushMs`、`camSrc`(用户补 H264)"
  },
  {
    "id": "screen-demo",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "录屏演示运镜",
    "triggerWhen": "演示软件/录屏 demo 的整段:口播缩到角落 + 大窗 3D 展示录屏",
    "parameterGuide": "`corner`(br右下/bl左下)、`title`(窗口标题)、`videoSrc`(留空,用户在 Studio 里填 `/demo/xxx.mp4`)、`showRing`(口播落位框,默认true)、`camSrc`(留空;用户在 Studio 传口播 H264 后,缩角运镜直接烤进导出,成片免对位)。**独占全屏,勿与其他卡同屏;时长跟整个演示段落走(常 15s+)**"
  },
  {
    "id": "demo-tour",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "demo 巡览运镜 · 黑底浮屏 3D 倾斜,镜头逐站推近讲解焦点",
    "triggerWhen": "一段录屏里有好几个焦点要讲,镜头逐站推近。**独占全屏**",
    "parameterGuide": "`vidRate`(录屏播放倍速)、`theme`(底色(此卡独立生效))、`videoSrc`(录屏路径(/demo/xxx.mp4))、`imgSrc`(截图路径(填了优先用图))、`stops`(巡览路线(每行:横偏%,纵偏%,放大))、`tourSec`(巡览总时长)、`tilt`(3D 倾斜幅度)、`panX`(焦点横移(推近各站整体))、`panY`(焦点纵移(推近各站整体))、`camSrc`(口播圆窗(留空导出用全局口播))、`accent`(强调色(圆窗描边))"
  },
  {
    "id": "cam-pan",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "全屏录屏运镜",
    "triggerWhen": "讲界面/网页/代码的 B-roll 段:镜头在录屏画面上慢推/漂移/斜切环绕",
    "parameterGuide": "`motion`(in推近/out拉远/drift-l左漂/drift-r右漂/tilt斜切环绕)、`zoom`(运镜幅度 1.05-1.6,默认1.18)、`moveSec`(运镜时长s,≈卡时长)、`videoSrc`(留空,Studio 里选文件)。**独占全屏,勿与其他卡同屏**"
  },
  {
    "id": "cam-frame",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "人物取景框 · A-Roll 收成圆/3:4竖框/圆角方并挪到一侧,另一半留给内容",
    "triggerWhen": "整段要把人收到一侧、另一半留给内容(整段常驻,不是瞬间效果)",
    "parameterGuide": "`shape`(取景形状)、`side`(落位)、`size`(框宽)、`camDX`(横向微调)、`camDY`(纵向微调)、`ring`(描边)、`accent`(强调色)、`camSrc`(口播视频(烤进导出))"
  },
  {
    "id": "focus-card",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "人物聚焦运镜",
    "triggerWhen": "抛出本段 2-3 个要点/议题的时刻:口播缩进一侧圆角框,另一侧要点逐条弹入(或留白叠其他卡)",
    "parameterGuide": "`bg`(cream米色/mist雾白/dark暗色)、`side`(left/right;right=口播缩右、左侧留白可叠动效卡)、`items`(`\\|`分隔,每条≤8字;空=留白)、`stepMs`(每条间隔,按SRT算)、`showRing`(默认true)、`camSrc`(留空;传口播后运镜烤进导出)。**独占全屏(留白侧可叠内容卡),常 8-15s**"
  },
  {
    "id": "focus-takeover",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "黑屏聚焦仪表盘:全屏压黑只留黄色准星圆窗露脸,右侧菜单逐项点亮(自动编号),下方砸两行大标题",
    "triggerWhen": "\"接下来讲这几件事\"的章节总起/悬念揭晓(4-8s);圆窗是透明挖孔,盖回原片自然露脸,交付说明提醒用户用 ringX/ringY 套住自己",
    "parameterGuide": "`items`(菜单`\\|`分隔)、`title`(上行`\\|`下行,`*词*`变黄)、`num`(左侧大编号)、`en`(右下竖排英文)、`ring`/`ringX`/`ringY`(圆窗大小与位置)、`stepMs`(菜单逐项,卡点用)。**独占全屏,勿与其他卡同屏**"
  },
  {
    "id": "cover-stack",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "封面叠放",
    "triggerWhen": "提到\"前几期视频/某篇文章/某个作品\"时:封面缩略图从侧边滑入叠放,人保持全屏",
    "parameterGuide": "`position`(left/right)、`cap1`/`cap2`(标注文字)、`img1`/`img2`(留空,用户在 Studio 里传图)、`stepMs`(每张间隔)"
  },
  {
    "id": "cover-flow",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "half 人下沉",
    "purpose": "封面流 · 3D 卡片横向轮播,居中一张正对镜头,两侧侧倾退后",
    "triggerWhen": "一次展示 3-5 个作品/封面/案例,**每张都要看清**(居中那张正对镜头,可放图或视频)。只要「这么多」的量感、单张看不清也行 → `proof-wall`;讲「前几期视频」顺手带过 → `cover-stack`",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`position`(落位)、`img1`(图/视频 1)、`cap1`(标题 1)、`img2`(图/视频 2)、`cap2`(标题 2)、`img3`(图/视频 3(可空))、`cap3`(标题 3(可空))、`img4`(图/视频 4(可空))、`cap4`(标题 4(可空))、`img5`(图/视频 5(可空))、`cap5`(标题 5(可空))、`showTitle`(显示标题)、`holdMs`(每张停留)、`cardW`(卡片宽)、`cardH`(卡片高)、`gap`(间距)、`tilt`(侧转角)、`sideTilt`(侧倾角)、`dim`(两侧压暗)、`depth`(纵深(两侧后退))、`radius`(圆角)、`accent`(强调色)"
  },
  {
    "id": "video-showcase",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "双屏展台 · 两条往期视频并排微倾同时放",
    "triggerWhen": "同时展示两条往期作品/两个案例,并排微倾一起放",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`clips`(素材(一行一块:路径/起始秒/标签))、`kicker`(左上角标(EN))、`kickerZh`(角标中文小字)、`startAt`(升起时刻(s))、`stepMs`(两块进场间隔)、`tilt`(向内倾斜(度))、`float`(呼吸幅度(px))、`safeBottom`(底部字幕安全区(%))、`bg`(全屏底)、`accent`(强调色)"
  },
  {
    "id": "clip-parade",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "素材墙收队 · 视频铺开 → 依次排队进侧栏",
    "triggerWhen": "一堆素材先铺开展示,再依次收队进侧栏,给结论让位",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`layout`(排布)、`img1`(① 视频/图)、`label1`(① 标签)、`clip1`(① 从第几秒开始播)、`w1`(① 大小(宽 px))、`x1`(① 横向(px))、`y1`(① 纵向(px))、`img2`(② 视频/图)、`label2`(② 标签)、`clip2`(② 从第几秒开始播)、`w2`(② 大小(宽 px))、`x2`(② 横向(px))、`y2`(② 纵向(px))、`img3`(③ 视频/图)、`label3`(③ 标签)、`clip3`(③ 从第几秒开始播)、`w3`(③ 大小(宽 px))、`x3`(③ 横向(px))、`y3`(③ 纵向(px))、`tileTilt`(随手歪斜(度))、`tiles`(整墙模式的素材(一行一块:路径/起始秒/标签))、`cols`(整墙列数)、`kicker`(左上角标(EN))、`kickerZh`(角标中文小字)、`buildAt`(开始进场(s))、`buildStepMs`(逐块进场间隔)、`paradeAt`(开始收队(s))、`paradeStepMs`(逐块收队间隔)、`listSide`(收队到哪一侧)、`titleEn`(收队后·EN 小字)、`title`(收队后·大标题)、`titleZh`(收队后·中文小字)、`safeTop`(顶部安全区(避开章节条 px))、`safeBottom`(底部字幕安全区(%))、`bg`(底幕颜色)、`bgAlpha`(底幕透明度)、`bgFeather`(底幕边缘羽化(px))、`bgInsetX`(底幕左右内缩(px))、`accent`(强调色)"
  },
  {
    "id": "demo-rail",
    "purposeGroup": "场景 · 运镜",
    "verticalPolicy": "still 不让",
    "purpose": "演示轨 · 录屏靠右微倾 + 左侧编号步骤链逐步点亮",
    "triggerWhen": "一段录屏要配「第 1 步/第 2 步」的步骤链同步点亮。**独占全屏**",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`scene`(场号(SCENE 01))、`sceneZh`(场号中文小字)、`steps`(步骤(一行一步:中文/EN/图标名))、`times`(每步点亮秒(/ 分隔))、`videoSrc`(录屏路径(/demo/xxx.mp4))、`clipStart`(素材起始秒)、`videoSrc2`(第 2 段录屏(可空))、`clipStart2`(第 2 段从第几秒开始播)、`videoSrc3`(第 3 段录屏(可空))、`clipStart3`(第 3 段从第几秒开始播)、`segSecs`(每段各播几秒(逗号分隔,如 3,4,3;留空=素材播完就换下一段))、`vidRate`(录屏播放倍速)、`tilt`(录屏窗倾斜(度))、`winW`(录屏窗放大(宽度 px))、`winAspect`(录屏画幅(和你的录屏对齐))、`fit`(画面怎么塞进窗口)、`winX`(录屏窗横移(px))、`winY`(录屏窗纵移(px))、`bullet`(步骤编号样式)、`safeBottom`(底部字幕安全区(%))、`bg`(全屏底)、`accent`(强调色)"
  },
  {
    "id": "terminal-3d",
    "purposeGroup": "场景 · B-roll",
    "verticalPolicy": "full 人缩小窗",
    "purpose": "3D 终端打字机",
    "triggerWhen": "讲命令行/代码执行过程;**模拟和 AI 的拉扯对话**(\"改→不对→再改→✗还是不对\"逐字打出,痛点共鸣神器,可当人物背景板:剪映智能抠像把人叠回终端上层)",
    "parameterGuide": "`file`(标题栏)、`lines`(`\\|`分隔;`$`提示符/用户`-`参数 `\"字符串\"` `#`注释 `❯`执行 `✓`成功 `✗`失败红)、`cps`(按卡片时长算:总字数÷时长)、`position`"
  },
  {
    "id": "project-window",
    "purposeGroup": "场景 · B-roll",
    "verticalPolicy": "full 人缩小窗",
    "purpose": "项目窗口",
    "triggerWhen": "讲\"创建/修改了哪些文件\"",
    "parameterGuide": "`title`、`files`(`文件名,动作`用`\\|`分隔;动作:新建/修改/整理/删除)、`position`"
  },
  {
    "id": "light-sweep",
    "purposeGroup": "转场",
    "verticalPolicy": "still 不让",
    "purpose": "光扫转场",
    "triggerWhen": "章节切换瞬间,1-1.5s 即可",
    "parameterGuide": "`theme`(底色(此卡独立生效))"
  },
  {
    "id": "warp-title",
    "purposeGroup": "转场",
    "verticalPolicy": "still 不让",
    "purpose": "星空穿梭标题 · 黑底星轨飞驰,大标题闪现微震(章节转场)",
    "triggerWhen": "章节转场的大标题,需要一个「跳到下一章」的强断点",
    "parameterGuide": "`title`(主标题)、`sub`(副题(留空不显示))、`accent`(强调色(副题/星轨点缀))、`speed`(穿梭速度)"
  },
  {
    "id": "burst-halo",
    "purposeGroup": "情绪爆点",
    "verticalPolicy": "half 人下沉",
    "purpose": "爆点光环:光环+放射线锚定人物 + 仪表小卡",
    "triggerWhen": "笑点/爆点/高能句(2-3s,用户会拖到人物身上)",
    "parameterGuide": "`text`(爆点大字如\"哈哈哈哈!\")、`showMeter`、`meterEn`/`meterZh`、`pct`、`accent`(默认orange)"
  },
  {
    "id": "ambient-wash",
    "purposeGroup": "氛围底噪",
    "verticalPolicy": "still 不让",
    "purpose": "氛围色洗:画面边缘泛语义色",
    "triggerWhen": "每章一张,随章节换色",
    "parameterGuide": "`style`(edges/left/right/top)、`strength`(0.2-0.35)、`accent`(=本章语义色)"
  },
  {
    "id": "dust-field",
    "purposeGroup": "氛围底噪",
    "verticalPolicy": "still 不让",
    "purpose": "尘埃流场 · 光尘缓缓上浮的全屏氛围底,分层做远近感",
    "triggerWhen": "整段需要一层安静的氛围底(回忆、沉淀、收尾),**不承载任何信息**。要跟着章节换语义色、有情绪推动 → `ambient-wash`",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`accent`(光尘颜色)、`count`(数量)、`rise`(上浮速度)、`drift`(横向漂移)、`size`(颗粒大小)、`glow`(发光)、`dim`(整体浓度)"
  },
  {
    "id": "letter-glitch",
    "purposeGroup": "氛围底噪",
    "verticalPolicy": "still 不让",
    "purpose": "字母矩阵背景",
    "triggerWhen": "B-roll 全屏科技背景(会盖住画面,只配 B-roll 段落,勿与其他卡同屏)",
    "parameterGuide": "`theme`(底色(此卡独立生效))、`flipMs`(翻动速度)、`density`(翻动密度)、`dim`(整体透明度)"
  }
] as const;
