// Generated from the Overlay Studio reference catalog. Keep this module free of React imports.
export const importedOverlayStudioEffects = [
  {
    "id": "glass-pane",
    "name": "玻璃底幕",
    "category": "标注",
    "description": "玻璃底幕 · 一侧黑玻璃渐变垫底,亮视频上给特效区压出暗底",
    "tags": [
      "Overlay Studio",
      "常驻层",
      "GlassPane",
      "玻璃虚化"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "玻璃底幕 · 一侧黑玻璃渐变垫底,亮视频上给特效区压出暗底",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "side": "left",
      "width": 34,
      "strength": 0.55,
      "blur": 0,
      "layer": "back"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "frost-screen",
    "name": "全屏毛玻璃",
    "category": "标注",
    "description": "全屏毛玻璃 · 整块画面虚化+黑/白玻璃底,让开顶部进度条",
    "tags": [
      "Overlay Studio",
      "常驻层",
      "FrostScreen",
      "玻璃虚化"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "全屏毛玻璃 · 整块画面虚化+黑/白玻璃底,让开顶部进度条",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "tone": "dark",
      "blur": 18,
      "alpha": 0.42,
      "topSafe": 48,
      "bottomSafe": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "info-board",
    "name": "累积信息板",
    "category": "卡片",
    "description": "累积信息板 · 论点板逐行点亮长驻留",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "InfoBoard",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 17800000,
    "defaultText": "head｜大标题写这一行｜强调词变红｜HEADLINE｜tag｜红框标签 · 给论点定性｜bar｜数据条的名目｜72｜72%｜kv｜大数字｜¥1,000 万｜小注跟在后面｜quote｜引语放这一行 一句就好｜署名 · 出处写在这｜ent｜｜",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "rows": "head|大标题写这一行|强调词变红|HEADLINE\ntag|红框标签 · 给论点定性\nbar|数据条的名目|72|72%\nkv|大数字|¥1,000 万|小注跟在后面\nquote|引语放这一行 一句就好|署名 · 出处写在这\nent||实体名牌写人名或机构|身份小注(头像传图后填路径)\nvs|72|28|比分行写名目\nline|早先 ✗ 第一次没成 ; 后来 ✓ 这次成了\nshift|前后对比|之前的值|之后的值\nstamp|盖章定论|STAMP\nseal|实心定论条|SEAL",
      "times": "0.3|2|3.6|5.2|6.8|8.4|10|11.6|13.2|14.8",
      "bg": "dark",
      "rowFx": "lit",
      "bgAlpha": 0.6,
      "grow": false,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "dot-crowd",
    "name": "点阵人群比",
    "category": "卡片",
    "description": "点阵人群比 · 大数字铺成点阵,红条黄字递进,巨型比率收尾",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "DotCrowd",
      "粒子流场",
      "滚动计数"
    ],
    "renderer": "react",
    "defaultDurationUs": 10500000,
    "defaultText": "总量的名目｜10 万+",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "title": "总量的名目|10 万+",
      "dots": 280,
      "sub1": "红条写占比|小注跟在后面|62",
      "sub2": "黄字行的名目 · 只有|三五百|个",
      "ratio": "100:1|巨型比率 · 一锤收尾",
      "times": "0.3|2.5|5|7.5",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "proof-shot",
    "name": "截图实证",
    "category": "卡片",
    "description": "截图实证 · 真实截图 + 认证章,用素材背书",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "ProofShot",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "图注写截图是什么、哪来的",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "top-right",
      "img1": "",
      "img2": "",
      "img3": "",
      "stepMs": 3000,
      "tag": "REAL · 角标写定性",
      "caption": "图注写截图是什么、哪来的",
      "captionEn": "SOURCE · EN NOTE",
      "marks": "",
      "enter": "slide",
      "growMs": 700,
      "w": 600,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "proof-wall",
    "name": "截图墙",
    "category": "卡片",
    "description": "截图墙 · 网友截图一张张弹出来,越堆越多,拼满半边屏",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "ProofWall",
      "堆叠累积"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "网友反馈 · FEEDBACK",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "side": "left",
      "img1": "",
      "img2": "",
      "img3": "",
      "img4": "",
      "img5": "",
      "img6": "",
      "img7": "",
      "img8": "",
      "img9": "",
      "img10": "",
      "times": "",
      "firstAt": 0.15,
      "stepMs": 260,
      "width": 50,
      "tilt": 2,
      "fit": "cover",
      "tag": "网友反馈 · FEEDBACK",
      "countZh": " 条好评",
      "safeBottom": 12,
      "bg": "dark",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "ghost-video",
    "name": "幽灵参考视频",
    "category": "卡片",
    "description": "幽灵参考视频 · 半透明+四边羽化融进画面,展示素材不压人脸",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "GhostVideo",
      "玻璃虚化"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "src": "",
      "side": "right",
      "top": 110,
      "w": 820,
      "opacity": 0.82,
      "feather": 90,
      "tilt": 14,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "phone-shot",
    "name": "手机壳证据",
    "category": "卡片",
    "description": "手机壳证据 · 评论/私信/聊天装进手机,多图翻页",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "PhoneShot",
      "翻转轮换"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "评论区 · 真实提问",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "right",
      "tag": "评论区 · 真实提问",
      "img1": "",
      "img2": "",
      "img3": "",
      "videoSrc": "",
      "stepMs": 3500,
      "glow": true,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "doc-scroll",
    "name": "文档滚动",
    "category": "卡片",
    "description": "文档滚动 · 原文/合同在窗口里缓缓滚过 + 高亮条",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "DocScroll",
      "扫过点亮"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "原文 · 来源归因写这里",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "right",
      "title": "原文 · 来源归因写这里",
      "img1": "",
      "scrollMs": 8000,
      "highlight": true,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "fact-stack",
    "name": "累积数字胶囊",
    "category": "卡片",
    "description": "累积数字胶囊 · 逐颗落地全程不消失",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "FactStack",
      "堆叠累积",
      "滚动计数"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "数字1 开头的胶囊｜数字2 跟着讲述落地｜数字3 全程不消失",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "bottom-left",
      "items": "数字1 开头的胶囊|数字2 跟着讲述落地|数字3 全程不消失",
      "stepMs": 2500,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "win-lose",
    "name": "胜负对比",
    "category": "卡片",
    "description": "胜负对比 · 胜者亮败者暗,层级即观点",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "WinLose",
      "对撞并置"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "胜者写这里",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "winName": "胜者写这里",
      "winNote": "选它的理由 · 小注一行",
      "winTag": "WINNER",
      "loseName": "败者写这里",
      "loseNote": "没选它的原因 · 小注一行",
      "loseTag": "NOT YET",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "rule-card",
    "name": "规则卡",
    "category": "卡片",
    "description": "规则卡 · 大绿勾主张 + 划掉的红色禁区",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "RuleCard",
      "对撞并置"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "绿勾写主张",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "text": "绿勾写主张",
      "subEn": "EN NOTE HERE",
      "bans": "划掉项一|划掉项二|划掉项三",
      "stepMs": 500,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "bar-race",
    "name": "条形赛跑",
    "category": "卡片",
    "description": "条形赛跑 · 逐条开跑,最大值自动橙色高亮",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "BarRace",
      "生长描画",
      "滚动计数"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "条目一 12｜条目二 48｜条目三 96",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "kicker": "EN KICKER · HERE",
      "kickerZh": "对比什么写在这",
      "rows": "条目一 12|条目二 48|条目三 96",
      "unit": "%",
      "stepMs": 600,
      "layout": "h",
      "topAccent": "green",
      "verdict": "✓ 结论写在这",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "photo-halo",
    "name": "照片环绕",
    "category": "卡片",
    "description": "照片环绕 · 一圈素材卡绕人物缓缓公转(配抠像在人身后)",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "PhotoHalo",
      "聚散飞行"
    ],
    "renderer": "react",
    "defaultDurationUs": 30000000,
    "defaultText": "照片环绕 · 一圈素材卡绕人物缓缓公转(配抠像在人身后)",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "img1": "",
      "img2": "",
      "img3": "",
      "img4": "",
      "img5": "",
      "img6": "",
      "stepMs": 260,
      "orbitSec": 36,
      "bob": 10,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "stick-fall",
    "name": "火柴人小剧场",
    "category": "卡片",
    "description": "火柴人小剧场 · 28 个动作任意串成一段戏,配道具和场景(卡点)",
    "tags": [
      "Overlay Studio",
      "证据实证",
      "StickFall",
      "堆叠累积"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "堆起来的东西写这里",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "acts": "0|举相机拍\n3|跪\n4.4|趴",
      "scene": "pile",
      "label": "堆起来的东西写这里",
      "pileMax": 18,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "metric-focus",
    "name": "核心数字动效",
    "category": "数据",
    "description": "核心数字动效 · 数字滚动聚焦",
    "tags": [
      "Overlay Studio",
      "数据指标",
      "MetricFocus",
      "滚动计数"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "大数字滚动定格,一行小字说明它为什么重要。",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "side": "left",
      "kicker": "核心数字",
      "value": 92.4,
      "decimals": 1,
      "suffix": "%",
      "caption": "大数字滚动定格,一行小字说明它为什么重要。",
      "duration": 1600,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "number-beats",
    "name": "大数字分点",
    "category": "数据",
    "description": "大数字分点 · 幽灵数字切换讲要点",
    "tags": [
      "Overlay Studio",
      "数据指标",
      "NumberBeats",
      "翻转轮换",
      "滚动计数"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "第一点,大数字滚出编号,短句跟上｜第二点,每一条卡在你开口的瞬间｜第三点,三条讲完正好收束",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "right",
      "points": "第一点,大数字滚出编号,短句跟上|第二点,每一条卡在你开口的瞬间|第三点,三条讲完正好收束",
      "holdMs": 2600,
      "loop": false,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "scale-swap",
    "name": "尺子换对了",
    "category": "数据",
    "description": "尺子换对了 · 同一数字两把刻度,假进度条现形",
    "tags": [
      "Overlay Studio",
      "数据指标",
      "ScaleSwap",
      "对撞并置"
    ],
    "renderer": "react",
    "defaultDurationUs": 10400000,
    "defaultText": "同一个数字｜换把尺子*结论就反了*",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "title": "同一个数字\n换把尺子*结论就反了*",
      "labelA": "尺子一 · 刻度画到 100 万",
      "pctA": 30,
      "tagA": "显示 30% · 看起来还很空",
      "markPct": 20,
      "markNote": "真正的临界点其实在这里",
      "labelB": "尺子二 · 刻度改到 20 万",
      "valB": "300K",
      "warnB": "该动手了",
      "foot": "同一个数字,只是把尺子换对了",
      "times": "0.3|1.2|3.2|5.2|7.4",
      "bgAlpha": 0.7,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "stack-share",
    "name": "占比拆解",
    "category": "数据",
    "description": "占比拆解 · 一根堆叠条看清钱花哪了",
    "tags": [
      "Overlay Studio",
      "数据指标",
      "StackShare",
      "堆叠累积"
    ],
    "renderer": "react",
    "defaultDurationUs": 9200000,
    "defaultText": "最大的一块｜占了 *58.8%*",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "kicker": "SHARE · 眉题写英文",
      "title": "最大的一块\n占了 *58.8%*",
      "segs": "58.8 占比最大的一项|24.2 第二项|16.2 第三项|0.8 剩下的",
      "bracketN": 2,
      "bracketText": "前两项合计 83%",
      "caption": "小注写口径:这组数字是怎么算出来的",
      "note": "*还能再补一段:*这一行放更长的说明,星号包住的词会变成强调色。",
      "times": "0.3|1.4|3.2|4.6|6.2",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "column-stack",
    "name": "逐轮堆叠柱",
    "category": "数据",
    "description": "逐轮堆叠柱 · 底层越垫越厚,新增只有薄薄一层",
    "tags": [
      "Overlay Studio",
      "数据指标",
      "ColumnStack",
      "堆叠累积"
    ],
    "renderer": "react",
    "defaultDurationUs": 8400000,
    "defaultText": "底下越垫越厚｜新增只有*薄薄一层*",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "kicker": "STACK · 眉题写英文",
      "title": "底下越垫越厚\n新增只有*薄薄一层*",
      "rounds": 12,
      "pow": 1.15,
      "legendA": "每轮新增的部分",
      "legendB": "一直累积下来的部分",
      "ticks": "第 1 轮|第 6 轮|第 12 轮",
      "foot": "脚注写这张图在说明什么",
      "times": "0.3|1.2|3.4|5.4",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "stair-bars",
    "name": "分档对比柱",
    "category": "数据",
    "description": "分档对比柱 · 绿到红逐级恶化,同指标不同档",
    "tags": [
      "Overlay Studio",
      "数据指标",
      "StairBars",
      "对撞并置",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 8200000,
    "defaultText": "同一件事｜从 3 变成 *9.3*",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "kicker": "LEVELS · 眉题写英文",
      "title": "同一件事\n从 3 变成 *9.3*",
      "vals": "3|4.8|9.3",
      "valTexts": "3s|4.8s|9.3s",
      "labels": "第一档|第二档|第三档",
      "colors": "var(--hud-green)|var(--hud-orange)|var(--hud-alert)",
      "grid": "3|6|9",
      "gridUnit": "s",
      "caption": "小注写这三档是按什么分的",
      "foot": "脚注写数据口径 · 星号包住的词会*变强调色*",
      "times": "0.3|1.3|3.4|5.2",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "multiply-grid",
    "name": "乘法成本",
    "category": "数据",
    "description": "乘法成本 · 方块阵 列×行,两个乘数是相乘不是相加",
    "tags": [
      "Overlay Studio",
      "数据指标",
      "MultiplyGrid",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 8600000,
    "defaultText": "两个因素叠在一起｜是*相乘*,不是相加",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "kicker": "MULTIPLY · 眉题写英文",
      "title": "两个因素叠在一起\n是*相乘*,不是相加",
      "gridCols": 2,
      "gridRows": 3,
      "result": "= 6 倍",
      "factor1": "因素一 2 倍",
      "factor2": "× 因素二 3 倍",
      "gridCaption": "一句话说明为什么相乘比相加狠",
      "statVal": "54",
      "statUnit": "%",
      "statText": "补一个数字佐证:*27%* 的量,吃掉了 *54%* 的成本",
      "times": "0.3|1.4|2.8|4.4|5.6",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "diverge-lines",
    "name": "双线分叉图",
    "category": "数据",
    "description": "双线分叉图 · 一升一降此消彼长;gap 模式一快一慢,红虚线量差距",
    "tags": [
      "Overlay Studio",
      "数据指标",
      "DivergeLines",
      "生长描画"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "mode": "split",
      "gapLabel": "",
      "kicker": "",
      "kickerZh": "",
      "aLabel": "升的量写这",
      "bLabel": "降的量写这",
      "aColor": "green",
      "bColor": "alert",
      "drawMs": 1600,
      "bg": "dark",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "drop-arrow",
    "name": "降幅大箭头",
    "category": "数据",
    "description": "降幅大箭头 · 前值→俯冲箭头→后值,巨号降幅百分比砸出",
    "tags": [
      "Overlay Studio",
      "数据指标",
      "DropArrow",
      "滚动计数"
    ],
    "renderer": "react",
    "defaultDurationUs": 7200000,
    "defaultText": "做了这件事｜*降幅很明显*",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "kicker": "DROP · 眉题写英文",
      "title": "做了这件事\n*降幅很明显*",
      "fromLabel": "改之前 · 中位数",
      "fromVal": "52万",
      "toLabel": "改之后",
      "toVal": "6.6万",
      "pct": "−88%",
      "pctNote": "降幅",
      "foot": "",
      "times": "0.3|1.4|2.8|4.2",
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "compare-split",
    "name": "左右对比卡",
    "category": "布局",
    "description": "左右对比卡 · 双项条形对照",
    "tags": [
      "Overlay Studio",
      "对比取舍",
      "CompareSplit",
      "对撞并置"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "前后对比",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "side": "right",
      "title": "前后对比",
      "aLabel": "用了之后",
      "aValue": 8600,
      "bLabel": "用之前",
      "bValue": 3200,
      "suffix": "",
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "cost-cut",
    "name": "成本压缩条",
    "category": "布局",
    "description": "成本压缩条 · 两条对比压到最短 + 结论巨字",
    "tags": [
      "Overlay Studio",
      "对比取舍",
      "CostCut",
      "对撞并置"
    ],
    "renderer": "react",
    "defaultDurationUs": 7200000,
    "defaultText": "OLD VS NEW",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "kicker": "OLD VS NEW",
      "kickerZh": "比什么的成本 · 写这",
      "oldZh": "旧做法",
      "oldEn": "OLD WAY",
      "oldPct": 100,
      "oldNote": "很贵",
      "newZh": "新做法",
      "newEn": "NEW WAY",
      "newPct": 12,
      "newNote": "很便宜",
      "newIcon": "bolt",
      "punch": "压到最低",
      "punchEn": "MIN",
      "oldAt": 0.3,
      "newAt": 2.2,
      "punchAt": 4.2,
      "arrow": true,
      "glass": "none",
      "glassAlpha": 0.6,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "compare-bars",
    "name": "派与不派",
    "category": "布局",
    "description": "派与不派 · 反例/正例徽标卡 + 一长一短量级条",
    "tags": [
      "Overlay Studio",
      "对比取舍",
      "CompareBars",
      "对撞并置"
    ],
    "renderer": "react",
    "defaultDurationUs": 8200000,
    "defaultText": "两种做法,*差一个量级*",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "kicker": "COMPARE · 眉题写英文",
      "title": "两种做法,*差一个量级*",
      "cardBad": "不这么做~问题写在这里~*后果*写在这里,星号会变色",
      "cardGood": "这么做~做法写在这里~*好处*写在这里,星号会变色",
      "barALabel": "做法 A · 每次平均",
      "barAVal": "243K",
      "barAPct": 100,
      "barBLabel": "做法 B · 每次平均",
      "barBVal": "52K",
      "barBPct": 21,
      "barNote": "轻约 5 倍",
      "times": "0.3|1.2|2.4|4.0|5.2",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "strike-flip",
    "name": "反转打脸卡",
    "category": "布局",
    "description": "反转打脸卡 · 划掉常识,砸出真相",
    "tags": [
      "Overlay Studio",
      "对比取舍",
      "StrikeFlip",
      "翻转轮换"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "旧认知 = 理所当然",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "aText": "旧认知 = 理所当然",
      "aText2": "",
      "aText3": "",
      "bText": "划掉它,砸出反转",
      "strikeAtMs": 1400,
      "strikeStepMs": 1400,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "icon-veto",
    "name": "图标打叉",
    "category": "布局",
    "description": "图标打叉 · 概念立起来,红✗划过图形化否定",
    "tags": [
      "Overlay Studio",
      "对比取舍",
      "IconVeto",
      "扫过点亮"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "被否定的概念?",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "icon": "train",
      "text": "被否定的概念?",
      "vetoAt": 1.2,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "quote-cite",
    "name": "引用卡",
    "category": "强调",
    "description": "引用卡 · 引用他人话/图/视频 + 来源",
    "tags": [
      "Overlay Studio",
      "金句观点",
      "QuoteCite",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "引用谁的话,原文放这里。",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "right",
      "media": "none",
      "quote": "引用谁的话,原文放这里。",
      "avatar": "名",
      "img1": "",
      "author": "被引用的人",
      "source": "身份头衔 · 内容出处",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "formula-pill",
    "name": "公式药丸",
    "category": "强调",
    "description": "公式药丸 · 图标 + A = B → C,一行讲完一个机制",
    "tags": [
      "Overlay Studio",
      "金句观点",
      "FormulaPill",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "起因写这 = 机制写这 → 结果写这",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "bottom",
      "icon": "people",
      "text": "起因写这 = 机制写这 → 结果写这",
      "resAccent": "green",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "kinetic-words",
    "name": "逐词大字钩子",
    "category": "强调",
    "description": "逐词大字钩子 · 词块按节奏砸出",
    "tags": [
      "Overlay Studio",
      "金句观点",
      "KineticWords",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "开场三秒｜一句设问｜把观众｜*钉在屏幕上*",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "chunks": "开场三秒|一句设问|把观众|*钉在屏幕上*",
      "holdMs": 750,
      "dimPast": true,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "karaoke-line",
    "name": "跟读高亮句",
    "category": "强调",
    "description": "跟读高亮句 · 说到哪个词点亮哪个",
    "tags": [
      "Overlay Studio",
      "金句观点",
      "KaraokeLine",
      "扫过点亮"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "关键的话｜逐词点亮｜让观众｜跟着你｜读完｜这一句",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "bottom",
      "words": "关键的话|逐词点亮|让观众|跟着你|读完|这一句",
      "wordMs": 420,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "word-spin",
    "name": "词槽轮换",
    "category": "强调",
    "description": "词槽轮换 · 固定句式垂直翻滚换词",
    "tags": [
      "Overlay Studio",
      "金句观点",
      "WordSpin",
      "翻转轮换"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "多种能力｜多个场景｜一串亮点｜不同人群",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "prefix": "一句话轮换",
      "words": "多种能力|多个场景|一串亮点|不同人群",
      "suffix": "",
      "spinMs": 900,
      "loop": true,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "clip-flow",
    "name": "素材流水线",
    "category": "卡片",
    "description": "素材流水线 · 传送带进机器/拖拽入库/扫描选中,全程连续动画",
    "tags": [
      "Overlay Studio",
      "步骤流程",
      "ClipFlow",
      "聚散飞行"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "AI",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "mode": "conveyor",
      "items": "mountain 标签写这里|aperture 竖线分条|globe|map",
      "label": "AI",
      "inLabel": "素材",
      "outLabel": "成片",
      "times": "",
      "periodSec": 2.2,
      "picks": "6|13",
      "zoneIcon": "",
      "hubX": 320,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "chat-volley",
    "name": "对话往返",
    "category": "卡片",
    "description": "对话往返 · 气泡在两端头徽间穿梭,落成记录,绿戳收尾(卡点)",
    "tags": [
      "Overlay Studio",
      "步骤流程",
      "ChatVolley",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "我",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "leftLabel": "我",
      "rightLabel": "AI",
      "leftImg": "",
      "rightImg": "",
      "stampIcon": "",
      "msgs": "L|左边说的话写这行\nR|右边回的话写这行",
      "times": "0.3|2",
      "counter": "来回 2 轮",
      "stampText": "达成",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "action-band",
    "name": "动作卡组",
    "category": "卡片",
    "description": "动作卡组 · 编号白卡×N + 红绿灯分级色带",
    "tags": [
      "Overlay Studio",
      "步骤流程",
      "ActionBand",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 9200000,
    "defaultText": "该怎么做",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "kicker": "ACTION · 眉题写英文",
      "title": "该怎么做",
      "badge": "动作",
      "cards": "第一件事~用「~」隔开:前面是卡片标题,后面是说明|第二件事~一张卡一个动作,讲到哪张亮哪张|第三件事~最多放三到四张",
      "band": "绿 · 安全 50 var(--hud-green)|黄 · 注意 25 var(--hud-orange)|红 · 危险 25 var(--hud-alert)",
      "bandCaption": "色带小注:说明这三档是怎么划分的",
      "foot": "脚注:一句话给出行动指令,*重点词加星号*",
      "times": "0.3|1.2|3.6|5.0|6.2",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "stepper-flow",
    "name": "步骤指示",
    "category": "卡片",
    "description": "步骤指示 · 编号圆点自动推进",
    "tags": [
      "Overlay Studio",
      "步骤流程",
      "StepperFlow",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "第一步｜第二步｜第三步｜完成",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "steps": "第一步|第二步|第三步|完成",
      "stepMs": 1400,
      "loop": false,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "studio-build",
    "name": "基建三拍",
    "category": "卡片",
    "description": "基建三拍 · 动效库铺开→收进编辑台→以后每条几分钟",
    "tags": [
      "Overlay Studio",
      "步骤流程",
      "StudioBuild",
      "聚散飞行"
    ],
    "renderer": "react",
    "defaultDurationUs": 10700000,
    "defaultText": "THE LOGIC · 这套逻辑",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "kicker": "THE LOGIC · 这套逻辑",
      "libEn": "STEP ONE",
      "libZh": "第一步做什么(换成你的话)",
      "deckEn": "STEP TWO",
      "deckZh": "第二步做什么(换成你的话)",
      "payEn": "THE PAYOFF",
      "payZh": "之后能省下什么",
      "chips": 12,
      "chipStepMs": 130,
      "libAt": 0.3,
      "deckAt": 4,
      "payAt": 7.7,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "replicate-loop",
    "name": "复刻入库",
    "category": "卡片",
    "description": "复刻入库 · 看到→扔给大模型→复刻出来,飞进素材库,库亮一格 +1",
    "tags": [
      "Overlay Studio",
      "步骤流程",
      "ReplicateLoop",
      "聚散飞行"
    ],
    "renderer": "react",
    "defaultDurationUs": 11200000,
    "defaultText": "REPLICATE · 这一段的眉题",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "kicker": "REPLICATE · 这一段的眉题",
      "stops": "第一步(换成你的话)|search\n第二步|brain\n第三步|spin",
      "stopsAt": "0.1|2.6|5.1",
      "cells": 12,
      "filled": 9,
      "intoAt": 6.5,
      "libZh": "落进哪里(换成你的话)",
      "libEn": "YOUR LIBRARY",
      "note": "补一句小注(可空)",
      "noteAt": 8.2,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "timeline-h",
    "name": "横版时间线",
    "category": "卡片",
    "description": "横版时间线 · 进度线生长 + 节点逐个立起",
    "tags": [
      "Overlay Studio",
      "步骤流程",
      "TimelineH",
      "生长描画",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "时间线 · 三天三件事",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "top",
      "kicker": "时间线 · 三天三件事",
      "stops": "周一,事件一,一句副标|周二,事件二,一句副标|周三,事件三,一句副标",
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "flow-chart",
    "name": "自绘流程图",
    "category": "卡片",
    "description": "自绘流程图 · 节点弹出 + 连线自绘",
    "tags": [
      "Overlay Studio",
      "步骤流程",
      "FlowChart",
      "生长描画"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "流程链条",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "stepMs": 300,
      "theme": "dark",
      "position": "right",
      "title": "流程链条",
      "nodes": "起点|关键动作|下一步|拿到结果",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "converge",
    "name": "汇聚结尾",
    "category": "卡片",
    "description": "汇聚结尾 · 能力飞向中心 + 金句落定",
    "tags": [
      "Overlay Studio",
      "步骤流程",
      "Converge",
      "聚散飞行"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "结论",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "core": "结论",
      "nodes": "观点|案例|数据|铺垫|情绪|悬念",
      "line": "整期内容,*汇成这一句*。",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "section-head",
    "name": "段头三件套",
    "category": "布局",
    "description": "段头三件套 · 竖色条+EN标签+中文标题,段落常驻;填编号变章头",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "SectionHead",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "top-left",
      "num": "",
      "en": "EN MONO LABEL",
      "zh": "段落标题 · *重点词*换色",
      "sub": "",
      "subAt": 0,
      "src": "",
      "size": "l",
      "accent": "blue",
      "shadow": "none",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "icon-swarm",
    "name": "图标群",
    "category": "布局",
    "description": "图标群 · 无底板 icon 词条分列点亮",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "IconSwarm",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "head": "",
      "headEn": "",
      "items": "",
      "startAt": 0.3,
      "stepMs": 420,
      "layout": "split",
      "foot": "",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "stroke-title",
    "name": "综艺花字",
    "category": "布局",
    "description": "综艺花字 · 粗字黑描边大标题,前缀小标签+多行逐行砸出",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "StrokeTitle",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "大标题*变色词*",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "top",
      "tag": "小标签",
      "text": "大标题*变色词*",
      "fill": "yellow",
      "accent": "blue",
      "size": 96,
      "stepMs": 900,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "duo-title",
    "name": "双色块标题",
    "category": "布局",
    "description": "双色块标题 · EN小标+两行色块大标题(黑底彩字/彩底黑字),一卡一对色",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "DuoTitle",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "EN SUBTITLE",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "top-left",
      "en": "EN SUBTITLE",
      "line1": "第一行",
      "line2": "第二行*变色*",
      "mode": "chip",
      "accentA": "orange",
      "accentB": "green",
      "grad": true,
      "chipShape": "slant",
      "chipDeco": "none",
      "chip1Bg": "none",
      "shadow": "none",
      "note": "补充说明写这里,不填就不显示。",
      "noteAt": 0.6,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "chip-cluster",
    "name": "胶囊组",
    "category": "布局",
    "description": "胶囊组 · 图标标签逐个定格弹入",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "ChipCluster",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "并列的几个场景",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "stepMs": 160,
      "theme": "dark",
      "position": "right",
      "title": "并列的几个场景",
      "chips": "pen,场景一|rocket,场景二|target,场景三",
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "glow-badges",
    "name": "发光圆徽",
    "category": "布局",
    "description": "发光圆徽 · 眉题+大标+发光圆图标逐个点亮",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "GlowBadges",
      "光效发光",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "KICKER · 眉题写这",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "bg": "dark",
      "kicker": "KICKER · 眉题写这",
      "tPre": "PRE",
      "tZh": "大标题写这里",
      "tEn": "FAINT EN SUBTITLE",
      "badges": "标签一,chat,圆徽的名字,小注写在下面|标签二,bolt,图标填矢量名,如 bolt 与 books|标签三,books,最多放四枚,按间隔逐个亮",
      "badgesAt": 0.8,
      "stepMs": 900,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "outline-tree",
    "name": "结构树",
    "category": "布局",
    "description": "结构树 · 连接线画出,子项逐层展开",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "OutlineTree",
      "生长描画",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "总-分结构放这里",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "root": "总-分结构放这里",
      "kids": "原因 A:每条*逐级展开*|原因 B:关键词可以*高亮*|原因 C:讲一条,长一条",
      "stepMs": 900,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "ecosystem-hub",
    "name": "生态连接图",
    "category": "布局",
    "description": "生态连接图 · 外部工具连线接入中心",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "EcosystemHub",
      "生长描画",
      "聚散飞行"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "中心",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "hub": "中心",
      "icons": "🔗,工具一|✉,工具二|📄,工具三|◎,工具四|▲,工具五|✱,工具六",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "magic-bento",
    "name": "便当格卡片墙",
    "category": "布局",
    "description": "便当格卡片墙 · 高亮逐格巡游",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "MagicBento",
      "扫过点亮"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "CORE,主打亮点,第一格最大,放最重要的｜02,亮点二,一句话说明｜03,亮点三,一句话说明｜04,亮点四,一句话说明｜05,亮点五,高亮会挨个巡游",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "cells": "CORE,主打亮点,第一格最大,放最重要的|02,亮点二,一句话说明|03,亮点三,一句话说明|04,亮点四,一句话说明|05,亮点五,高亮会挨个巡游",
      "spotMs": 1100,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "quad-map",
    "name": "四象限图",
    "category": "布局",
    "description": "四象限图 · 纸面四宫格按卡点依次描边画出(末格黑底)",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "QuadMap",
      "生长描画"
    ],
    "renderer": "react",
    "defaultDurationUs": 10200000,
    "defaultText": "CELL ONE｜italic side note｜第一格中文名｜每格按卡点描边画出｜CELL TWO｜draws on your cue｜第二格中文名｜讲到哪格 哪格出现｜CELL THREE｜icons are built in｜第三格",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "cells": "CELL ONE|italic side note|第一格中文名|每格按卡点描边画出\nCELL TWO|draws on your cue|第二格中文名|讲到哪格 哪格出现\nCELL THREE|icons are built in|第三格中文名|四个手绘图标自动配\nCELL FOUR|auto dark|第四格中文名|末格自动黑底反白",
      "times": "0.3|2.6|4.9|7.2",
      "dockTimes": "",
      "notes": "",
      "noteStepMs": 2400,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "map-territory",
    "name": "地图与疆域",
    "category": "布局",
    "description": "地图与疆域 · 标题横杠+逐条列举+图像画出,unknowns 箭头点题",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "MapTerritory",
      "生长描画",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 12400000,
    "defaultText": "MAP",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "times": "0.3|1.2|3.4|4.4|7.4|9.4",
      "itemStepMs": 1200,
      "mapEn": "MAP",
      "mapZh": "左面板 · 比喻/模型这一侧",
      "mapItems": "💬,条目逐条弹入|⚡,图标+短词|📚,最多放三条",
      "terrEn": "TERRITORY",
      "terrZh": "右面板 · 现实这一侧",
      "terrItems": "📁,同样三段式|🌍,标题先出条目后出|⛓️,图形最后画",
      "gapZh": "两图间的 gap 点题",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "card-swap",
    "name": "卡片轮换",
    "category": "布局",
    "description": "卡片轮换 · 堆叠卡定时换面",
    "tags": [
      "Overlay Studio",
      "信息结构",
      "CardSwap",
      "翻转轮换"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "01 · 要点,标题放这里,轮到它就滑到最前面｜02 · 要点,第二张卡,堆叠着轮流上前｜03 · 要点,第三张卡,切换节奏跟着讲述走",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "right",
      "cards": "01 · 要点,标题放这里,轮到它就滑到最前面|02 · 要点,第二张卡,堆叠着轮流上前|03 · 要点,第三张卡,切换节奏跟着讲述走",
      "swapMs": 2400,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "icon-pop",
    "name": "App 图标弹出",
    "category": "标注",
    "description": "App 图标弹出 · 大圆角图标在头旁弹出轻漂",
    "tags": [
      "Overlay Studio",
      "教程标注",
      "IconPop",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "App 图标弹出 · 大圆角图标在头旁弹出轻漂",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "img1": "",
      "position": "left",
      "size": 260,
      "bob": 8,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "marker-highlight",
    "name": "关键词圈注",
    "category": "标注",
    "description": "关键词圈注 · 马克笔/下划线扫过重点",
    "tags": [
      "Overlay Studio",
      "教程标注",
      "MarkerHighlight",
      "扫过点亮"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "一整句话里,用马克笔圈出*最重要的那几个字*。",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "top",
      "style": "marker",
      "text": "一整句话里,用马克笔圈出*最重要的那几个字*。",
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "steer-hint",
    "name": "引导提示卡",
    "category": "标注",
    "description": "引导提示卡 · 标题条 + 要点逐条滑入",
    "tags": [
      "Overlay Studio",
      "教程标注",
      "SteerHint",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "操作提示",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "right",
      "head": "操作提示",
      "lead": "教观众做一件事:标题条 + 一句引导 + 勾选要点。",
      "points": "第一步这样做|第二步跟上|做完就打勾",
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "pain-points",
    "name": "痛点清单卡",
    "category": "标注",
    "description": "痛点清单卡 · 问题逐条累积 + 扎心后果",
    "tags": [
      "Overlay Studio",
      "教程标注",
      "PainPoints",
      "逐条落位",
      "堆叠累积"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "后果,一句话砸实",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "stepMs": 180,
      "theme": "dark",
      "position": "left",
      "kicker": "你是不是也这样?",
      "pains": "痛点一:一句话扎心|痛点二:层层递进|痛点三:推向那个后果",
      "result": "后果,一句话砸实",
      "mark": "alert",
      "resAccent": "alert",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "decrypt-text",
    "name": "解密文字",
    "category": "标题",
    "description": "解密文字 · 乱码逐字解密成真文字",
    "tags": [
      "Overlay Studio",
      "文字进场",
      "DecryptText",
      "故障噪点",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "科技感揭晓:*乱码里解出答案*",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "kicker": "REVEAL",
      "text": "科技感揭晓:*乱码里解出答案*",
      "lockMs": 90,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "true-focus",
    "name": "焦点扫词",
    "category": "标题",
    "description": "焦点扫词 · 对焦框逐词跳,其余虚化",
    "tags": [
      "Overlay Studio",
      "文字进场",
      "TrueFocus",
      "扫过点亮",
      "玻璃虚化"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "逐词｜咀嚼｜强调",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "words": "逐词|咀嚼|强调",
      "focusMs": 900,
      "loop": true,
      "accent": "blue",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "char-assemble",
    "name": "字符聚拢",
    "category": "标题",
    "description": "字符聚拢 · 关键词的字四散飞聚",
    "tags": [
      "Overlay Studio",
      "文字进场",
      "CharAssemble",
      "聚散飞行"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "重磅关键词,聚拢出场",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "lead": "重磅关键词,聚拢出场",
      "word": "一锤定音",
      "wordAt": 0,
      "accent": "blue",
      "hotAccent": "ink",
      "glass": "none",
      "glassAlpha": 0.6,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "word-flank",
    "name": "巨字夹脸",
    "category": "标题",
    "description": "巨字夹脸 · 巨型大字一左一右砸在人物两侧(综艺感)",
    "tags": [
      "Overlay Studio",
      "文字进场",
      "WordFlank",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "大｜字",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "words": "大|字",
      "tone": "gold",
      "stepMs": 320,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "hand-lift",
    "name": "手托展示",
    "category": "场景",
    "description": "手托展示 · 左右手各托起一个图标+名字",
    "tags": [
      "Overlay Studio",
      "人物锚定",
      "HandLift",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "aperture",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "leftIcon": "aperture",
      "leftName": "LEFT",
      "leftNote": "左手托这个",
      "rightIcon": "code",
      "rightName": "RIGHT",
      "rightNote": "右手托这个",
      "leftAt": 0.2,
      "rightAt": 1.2,
      "leftX": -520,
      "leftY": 40,
      "rightX": 520,
      "rightY": 40,
      "swap": false,
      "glow": true,
      "float": 7,
      "accent": "blue"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "punch-zoom",
    "name": "镜头推近",
    "category": "场景",
    "description": "镜头推近 · 金句/爆点快推定住,烤进导出",
    "tags": [
      "Overlay Studio",
      "人物锚定",
      "PunchZoom",
      "推近定格"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "镜头推近 · 金句/爆点快推定住,烤进导出",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "camSrc": "",
      "amount": 1.15,
      "focus": "center",
      "pushMs": 1400,
      "accent": "blue"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "screen-demo",
    "name": "录屏演示运镜",
    "category": "场景",
    "description": "录屏演示运镜 · 口播缩角 + 大窗 3D 展示",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "ScreenDemo",
      "3D 浮屏",
      "取景重构"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "你的软件画面 — 录屏演示",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "corner": "br",
      "orient": "landscape",
      "winRatio": "auto",
      "winSize": 82,
      "title": "你的软件画面 — 录屏演示",
      "videoSrc": "",
      "camSrc": "",
      "bg": "dark",
      "accent": "blue",
      "showRing": true,
      "zooms": "",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "demo-tour",
    "name": "demo 巡览运镜",
    "category": "场景",
    "description": "demo 巡览运镜 · 黑底浮屏 3D 倾斜,镜头逐站推近讲解焦点",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "DemoTour",
      "3D 浮屏",
      "推近定格"
    ],
    "renderer": "react",
    "defaultDurationUs": 12000000,
    "defaultText": "0,0,1｜-16,-6,1.55｜4,8,1.9｜15,-2,2.15",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "videoSrc": "",
      "vidRate": 1,
      "imgSrc": "",
      "stops": "0,0,1\n-16,-6,1.55\n4,8,1.9\n15,-2,2.15",
      "tourSec": 9,
      "tilt": 7,
      "camSrc": "",
      "panX": 0,
      "panY": 0,
      "accent": "blue"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "cam-pan",
    "name": "全屏录屏运镜",
    "category": "场景",
    "description": "全屏录屏运镜 · 慢推近/漂移/斜切环绕",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "CamPan",
      "推近定格"
    ],
    "renderer": "react",
    "defaultDurationUs": 11000000,
    "defaultText": "全屏录屏运镜 · 慢推近/漂移/斜切环绕",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "videoSrc": "",
      "motion": "in",
      "zoom": 1.18,
      "moveSec": 8,
      "fadeOut": 0.4
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "cam-frame",
    "name": "人物取景框",
    "category": "场景",
    "description": "人物取景框 · A-Roll 收成圆/3:4竖框/圆角方并挪到一侧,另一半留给内容",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "CamFrame",
      "取景重构"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "人物取景框 · A-Roll 收成圆/3:4竖框/圆角方并挪到一侧,另一半留给内容",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "shape": "circle",
      "side": "left",
      "size": 520,
      "camDX": 0,
      "camDY": 0,
      "ring": true,
      "camSrc": "",
      "accent": "blue"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "focus-takeover",
    "name": "黑屏聚焦仪表盘",
    "category": "场景",
    "description": "黑屏聚焦仪表盘 · 全屏压黑只留准星圆窗,菜单逐项点亮",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "FocusTakeover",
      "玻璃虚化",
      "取景重构"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "大标题在这 *变黄词*｜第二行小一号",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "items": "菜单一|菜单二|菜单三",
      "title": "大标题在这 *变黄词*|第二行小一号",
      "en": "EDIT",
      "num": "01",
      "ring": 460,
      "ringX": 0,
      "ringY": 0,
      "stepMs": 700,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "cover-stack",
    "name": "封面叠放",
    "category": "场景",
    "description": "封面叠放 · 引用往期/文章,缩略图侧滑入",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "CoverStack",
      "堆叠累积"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "往期视频 · 标注放这里",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "left",
      "shape": "wide",
      "img1": "",
      "cap1": "往期视频 · 标注放这里",
      "img2": "",
      "cap2": "",
      "stepMs": 280,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "cover-flow",
    "name": "封面流",
    "category": "场景",
    "description": "封面流 · 3D 卡片横向轮播,居中一张正对镜头,两侧侧倾退后",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "CoverFlow",
      "3D 浮屏",
      "翻转轮换"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "标题写这行",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "img1": "",
      "cap1": "标题写这行",
      "img2": "",
      "cap2": "第二张",
      "img3": "",
      "cap3": "第三张",
      "img4": "",
      "cap4": "",
      "img5": "",
      "cap5": "",
      "holdMs": 1600,
      "cardW": 400,
      "cardH": 400,
      "gap": 8,
      "tilt": 12,
      "sideTilt": 8,
      "dim": 60,
      "depth": 540,
      "radius": 3,
      "showTitle": true,
      "accent": "blue",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "video-showcase",
    "name": "双屏展台",
    "category": "场景",
    "description": "双屏展台 · 两条往期视频并排微倾同时放",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "VideoShowcase",
      "3D 浮屏"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "clips": "",
      "frameRatio": "16:9",
      "layout": "auto",
      "offsetX": 0,
      "offsetY": 0,
      "kicker": "",
      "kickerZh": "",
      "startAt": 0.2,
      "stepMs": 260,
      "tilt": 7,
      "float": 6,
      "safeBottom": 12,
      "bg": "dark",
      "accent": "blue"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "clip-parade",
    "name": "素材墙收队",
    "category": "场景",
    "description": "素材墙收队 · 视频铺开 → 依次排队进侧栏",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "ClipParade",
      "聚散飞行"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "layout": "free",
      "tiles": "",
      "cols": 3,
      "img1": "",
      "clip1": 0,
      "label1": "",
      "x1": 90,
      "y1": 150,
      "w1": 720,
      "img2": "",
      "clip2": 0,
      "label2": "",
      "x2": 950,
      "y2": 130,
      "w2": 800,
      "img3": "",
      "clip3": 0,
      "label3": "",
      "x3": 430,
      "y3": 520,
      "w3": 700,
      "tileTilt": 2,
      "kicker": "",
      "kickerZh": "",
      "buildAt": 0.2,
      "buildStepMs": 400,
      "paradeAt": 6,
      "paradeStepMs": 140,
      "listSide": "right",
      "titleEn": "",
      "title": "",
      "titleZh": "",
      "safeTop": 64,
      "safeBottom": 12,
      "bg": "dark",
      "bgAlpha": 0.92,
      "bgFeather": 90,
      "bgInsetX": 0,
      "accent": "blue"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "demo-rail",
    "name": "演示轨",
    "category": "场景",
    "description": "演示轨 · 录屏靠右微倾 + 左侧编号步骤链逐步点亮",
    "tags": [
      "Overlay Studio",
      "场景 · 运镜",
      "DemoRail",
      "3D 浮屏",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "scene": "",
      "sceneZh": "",
      "steps": "",
      "times": "",
      "videoSrc": "",
      "clipStart": 0,
      "tilt": 6,
      "videoSrc2": "",
      "clipStart2": 0,
      "videoSrc3": "",
      "clipStart3": 0,
      "segSecs": "",
      "vidRate": 1,
      "winW": 1180,
      "winAspect": "16/9",
      "fit": "contain",
      "winX": 0,
      "winY": 0,
      "bullet": "num",
      "zooms": "",
      "safeBottom": 12,
      "bg": "dark",
      "accent": "blue"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "project-window",
    "name": "项目窗口",
    "category": "场景",
    "description": "项目窗口 · 文件行逐条掉入 + 动作标签",
    "tags": [
      "Overlay Studio",
      "场景 · B-roll",
      "ProjectWindow",
      "逐条落位"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "项目窗口 — 文件变更",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "position": "center",
      "title": "项目窗口 — 文件变更",
      "files": "新建的文件.md,新建|改过的文件.js,修改|整理的文件.css,整理|删掉的文件.txt,删除",
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "light-sweep",
    "name": "光扫转场",
    "category": "场景",
    "description": "光扫转场 · 一道斜光扫过画面",
    "tags": [
      "Overlay Studio",
      "转场",
      "LightSweep",
      "扫过点亮",
      "光效发光"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "光扫转场 · 一道斜光扫过画面",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "warp-title",
    "name": "星空穿梭标题",
    "category": "场景",
    "description": "星空穿梭标题 · 黑底星轨飞驰,大标题闪现微震(章节转场)",
    "tags": [
      "Overlay Studio",
      "转场",
      "WarpTitle",
      "粒子流场",
      "推近定格"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "《标题写在这里》",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "title": "《标题写在这里》",
      "sub": "副标题",
      "accent": "blue",
      "speed": 1
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "burst-halo",
    "name": "爆点光环",
    "category": "强调",
    "description": "爆点光环 · 光环+放射线锚定人物,笑点必炸",
    "tags": [
      "Overlay Studio",
      "情绪爆点",
      "BurstHalo",
      "光效发光"
    ],
    "renderer": "react",
    "defaultDurationUs": 6000000,
    "defaultText": "笑点那句话",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "text": "笑点那句话",
      "showRing": true,
      "showMeter": true,
      "meterEn": "PUNCH · DETECTED",
      "meterZh": "爆发点已锁定",
      "pct": 97,
      "accent": "blue",
      "meterX": 0,
      "meterY": 0,
      "offsetX": 0,
      "offsetY": 0
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "ambient-wash",
    "name": "氛围色洗",
    "category": "背景",
    "description": "氛围色洗 · 画面边缘泛语义色,情绪跟章节走",
    "tags": [
      "Overlay Studio",
      "氛围底噪",
      "AmbientWash",
      "光效发光"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "氛围色洗 · 画面边缘泛语义色,情绪跟章节走",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "style": "edges",
      "strength": 0.28,
      "accent": "blue"
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "dust-field",
    "name": "尘埃流场",
    "category": "背景",
    "description": "尘埃流场 · 光尘缓缓上浮的全屏氛围底,分层做远近感",
    "tags": [
      "Overlay Studio",
      "氛围底噪",
      "DustField",
      "粒子流场"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "尘埃流场 · 光尘缓缓上浮的全屏氛围底,分层做远近感",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "accent": "blue",
      "count": 70,
      "rise": 26,
      "drift": 40,
      "size": 2.4,
      "glow": 10,
      "dim": 70
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  },
  {
    "id": "letter-glitch",
    "name": "字母矩阵",
    "category": "背景",
    "description": "字母矩阵 · B-roll 全屏科技背景",
    "tags": [
      "Overlay Studio",
      "氛围底噪",
      "LetterGlitch",
      "故障噪点"
    ],
    "renderer": "react",
    "defaultDurationUs": 10000000,
    "defaultText": "字母矩阵 · B-roll 全屏科技背景",
    "defaultColor": "#ffffff",
    "defaultAccentColor": "#5fa0fa",
    "defaultParams": {
      "theme": "dark",
      "flipMs": 160,
      "density": 12,
      "dim": 70
    },
    "recipe": {
      "layout": "frame",
      "entrance": "none",
      "paddingX": 0,
      "paddingY": 0,
      "borderWidth": 0,
      "borderRadius": 0,
      "backgroundOpacity": 0
    }
  }
] as const;

export const importedOverlayStudioEffectIds = importedOverlayStudioEffects.map((effect) => effect.id);

export const importedOverlayStudioTextParamKeys: Readonly<Record<string, string>> = {
  "info-board": "rows",
  "dot-crowd": "title",
  "proof-shot": "caption",
  "proof-wall": "tag",
  "ghost-video": "src",
  "phone-shot": "tag",
  "doc-scroll": "title",
  "fact-stack": "items",
  "win-lose": "winName",
  "rule-card": "text",
  "bar-race": "rows",
  "stick-fall": "label",
  "metric-focus": "caption",
  "number-beats": "points",
  "scale-swap": "title",
  "stack-share": "title",
  "column-stack": "title",
  "stair-bars": "title",
  "multiply-grid": "title",
  "diverge-lines": "kicker",
  "drop-arrow": "title",
  "compare-split": "title",
  "cost-cut": "kicker",
  "compare-bars": "title",
  "strike-flip": "aText",
  "icon-veto": "text",
  "quote-cite": "quote",
  "formula-pill": "text",
  "kinetic-words": "chunks",
  "karaoke-line": "words",
  "word-spin": "words",
  "clip-flow": "label",
  "chat-volley": "leftLabel",
  "action-band": "title",
  "stepper-flow": "steps",
  "studio-build": "kicker",
  "replicate-loop": "kicker",
  "timeline-h": "kicker",
  "flow-chart": "title",
  "converge": "core",
  "section-head": "num",
  "icon-swarm": "items",
  "stroke-title": "text",
  "duo-title": "en",
  "chip-cluster": "title",
  "glow-badges": "kicker",
  "outline-tree": "root",
  "ecosystem-hub": "hub",
  "magic-bento": "cells",
  "quad-map": "cells",
  "map-territory": "mapEn",
  "card-swap": "cards",
  "marker-highlight": "text",
  "steer-hint": "head",
  "pain-points": "result",
  "decrypt-text": "text",
  "true-focus": "words",
  "char-assemble": "lead",
  "word-flank": "words",
  "hand-lift": "leftIcon",
  "screen-demo": "title",
  "demo-tour": "stops",
  "focus-takeover": "title",
  "cover-stack": "cap1",
  "cover-flow": "cap1",
  "video-showcase": "kicker",
  "clip-parade": "title",
  "demo-rail": "steps",
  "project-window": "title",
  "warp-title": "title",
  "burst-halo": "text"
};

export const importedOverlayStudioBackgroundIds: readonly string[] = [
  "glass-pane",
  "frost-screen",
  "ambient-wash",
  "dust-field",
  "letter-glitch"
];
