import {
  AlignJustify, Aperture, ArrowDownToDot, AudioLines, BadgePercent, Blend, BookOpenText, Box, Boxes, Captions, ChartBarBig, ChartGantt, ChartNoAxesColumnIncreasing, ChartPie, ChartSpline, ChevronsUpDown, CirclePause, Crosshair, Disc3, Flashlight, Focus, Frame, Gauge, GlassWater, Grid2x2, Grid3x3, Hash, Highlighter, Image, Images, Keyboard, Layers, Layers2, LayoutGrid, ListChecks, MessageSquare, MousePointerClick, Move3d, MoveHorizontal, MoveVertical, Music2, Network, Orbit, PaintBucket, PanelTop, PanelsTopLeft, Parentheses, PartyPopper, PencilLine, PencilRuler, PenTool, Pill, Printer, Projector, Quote, Rabbit, Radio, Rocket, Rotate3d, Route, Rows3, ScanLine, Scissors, Share2, Shapes, Shuffle, SlidersHorizontal, Sparkle, Sparkles, Spline, SquareCheck, SquareDashed, SquareDashedBottom, SquareSplitHorizontal, SquareSplitVertical, SquareStack, SquareTerminal, Stamp, StickyNote, StretchHorizontal, SunDim, SunMoon, Swords, Timer, Type, TypeOutline, Underline, UserRound, Wallpaper, Wind, Zap, ZoomIn, ZoomOut,
  type LucideIcon
} from "lucide-react";
import type { EffectGlyphKey } from "@/domain/effectGlyph";

/** 语义图标到 lucide 的映射；每个 key 都必须是可渲染的矢量图标，避免出现空白缩略图。 */
export const EFFECT_GLYPH_ICONS: Readonly<Record<EffectGlyphKey, LucideIcon>> = {
  "camera-push": ZoomIn,
  "camera-pull": ZoomOut,
  "camera-pan": MoveHorizontal,
  "camera-tilt": MoveVertical,
  "camera-orbit": Orbit,
  "camera-depth": Layers2,
  "camera-travel": Rocket,
  "camera-overhead": ArrowDownToDot,
  "camera-freeze": CirclePause,
  "camera-frame": Focus,
  "camera-reticle": Crosshair,
  "type-typewriter": Type,
  "type-assemble": TypeOutline,
  "type-underline": Underline,
  "type-highlight": Highlighter,
  "type-fill": PaintBucket,
  "type-glitch": Shuffle,
  "type-flip": Rows3,
  "type-mask": SquareDashed,
  "type-roll": ChevronsUpDown,
  "type-outline": PenTool,
  "type-stretch": StretchHorizontal,
  "type-path": Spline,
  "type-count": Timer,
  "type-quote": Quote,
  "type-marquee": AlignJustify,
  "type-caption": Captions,
  "type-bracket": Parentheses,
  "data-counter": Hash,
  "data-bar": ChartNoAxesColumnIncreasing,
  "data-ring": ChartPie,
  "data-line": ChartSpline,
  "data-gauge": Gauge,
  "data-grid": Grid3x3,
  "data-odometer": BadgePercent,
  "data-timeline": ChartGantt,
  "data-rank": ChartBarBig,
  "transition-wipe": SquareSplitVertical,
  "transition-flash": Zap,
  "transition-iris": Aperture,
  "transition-cube": Box,
  "transition-page": BookOpenText,
  "transition-glitch": ScanLine,
  "transition-cut": Scissors,
  "transition-mask": Blend,
  "transition-travel": Route,
  "ui-stack": SquareStack,
  "ui-grid": LayoutGrid,
  "ui-list": ListChecks,
  "ui-panel": PanelTop,
  "ui-morph": Shapes,
  "ui-skeleton": SquareDashedBottom,
  "ui-cursor": MousePointerClick,
  "ui-pill": Pill,
  "ui-window": PanelsTopLeft,
  "ui-select": SquareCheck,
  "ui-dial": Disc3,
  "ui-key": Keyboard,
  "ui-carousel": Images,
  "ui-segment": SlidersHorizontal,
  "ui-card": StickyNote,
  "ui-flip": Rotate3d,
  "ui-compare": SquareSplitHorizontal,
  "ui-scatter": Move3d,
  "ui-terminal": SquareTerminal,
  "light-glow": Sparkles,
  "light-sweep": SunDim,
  "light-spot": Flashlight,
  "light-particle": Sparkle,
  "light-ripple": Radio,
  "light-flyline": Share2,
  "effect-impact": Swords,
  "effect-bounce": PartyPopper,
  "effect-print": Printer,
  "effect-motion-blur": Wind,
  "shape-draw": PencilRuler,
  "shape-fracture": Boxes,
  "shape-hub": Network,
  "rhythm-beat": Music2,
  "rhythm-montage": Grid2x2,
  "rhythm-speed": Rabbit,
  "rhythm-strobe": SunMoon,
  "person-avatar": UserRound,
  "person-chat": MessageSquare,
  "brand-logo": Stamp,
  "brand-frame": Frame,
  "annotate-mark": PencilLine,
  "background-texture": Wallpaper,
  "background-photo": Image,
  "background-glass": GlassWater,
  "background-scene": Layers,
  "scene-3d": Projector,
  "media-audio": AudioLines
};

/** key 前缀就是缩略图的装饰族，用于 CSS 给不同品类不同的底纹。 */
export function effectGlyphFamily(glyph: EffectGlyphKey) {
  return glyph.slice(0, glyph.indexOf("-"));
}

export function EffectGlyphIcon({ glyph, size = 18 }: { glyph: EffectGlyphKey; size?: number }) {
  const Icon = EFFECT_GLYPH_ICONS[glyph];
  return <Icon size={size} strokeWidth={1.75} aria-hidden="true" />;
}
