import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { ShotcraftPlannerDialog } from "@/components/ShotcraftPlannerDialog";
import { createEmptyProject } from "@/domain/project";
import { DEFAULT_SETTINGS } from "@/services/storage";
import { useEditorStore } from "@/stores/editorStore";
import { generateShotcraftPlan } from "@/services/ai/shotcraft";
import { analyseMusicAsset } from "@/services/musicBeats";
import { hasApiKey } from "@/services/ai/provider";

vi.mock("@/services/ai/shotcraft", () => ({ generateShotcraftPlan: vi.fn() }));
vi.mock("@/services/ai/provider", () => ({ hasApiKey: vi.fn(async () => true) }));
vi.mock("@/services/musicBeats", () => ({ analyseMusicAsset: vi.fn() }));
const settings = { ...DEFAULT_SETTINGS, aiProvider: { ...DEFAULT_SETTINGS.aiProvider, model: "test" } };
const plan = { title: "产品标题", scenes: [{ shotId: "shotcraft-blur-slide", text: "用户内容", durationSeconds: 4, copy: [], bindings: [], regions: [], transition: "none", sounds: [], reason: "标题开场" }] };
beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(hasApiKey).mockResolvedValue(true);
  useEditorStore.setState({ project: createEmptyProject(), past: [], future: [], selectedClipId: null, selectedClipIds: [], playheadUs: 0 });
});
it("未配置云端 AI 也能单独分析音乐，失败可重试且不改变工程", async () => {
  vi.mocked(hasApiKey).mockResolvedValue(false);
  useEditorStore.setState({ project: { ...createEmptyProject(), assets: [{ id: "local-music", kind: "audio", name: "测试音乐", durationUs: 60_000_000, objectUrl: "blob:music" }] } });
  vi.mocked(analyseMusicAsset).mockRejectedValueOnce(new Error("音乐分析失败，请重试")).mockResolvedValueOnce({ version: 1, durationUs: 60_000_000, bpm: 100, phaseUs: 0, reliableGrid: true, candidates: [], beatsUs: [0, 600_000], hits: [], energy: [] });
  render(<ShotcraftPlannerDialog open settings={DEFAULT_SETTINGS} onOpenChange={vi.fn()} onNeedSettings={vi.fn()} />);
  fireEvent.pointerDown(screen.getByRole("combobox", { name: "编排背景音乐" }), { button: 0, pointerType: "mouse", ctrlKey: false });
  fireEvent.click(await screen.findByRole("option", { name: "测试音乐" }));
  fireEvent.click(screen.getByRole("button", { name: "分析拍点" }));
  expect(await screen.findByRole("alert")).toHaveTextContent("音乐分析失败，请重试");
  fireEvent.click(screen.getByRole("button", { name: "分析拍点" }));
  expect(await screen.findByText(/100.00 BPM/u)).toBeVisible();
  expect(generateShotcraftPlan).not.toHaveBeenCalled();
  expect(hasApiKey).not.toHaveBeenCalled();
  expect(useEditorStore.getState().past).toHaveLength(0);
});
it("显示实际编排后，用户加入才提交，并支持撤销", async () => {
  vi.mocked(generateShotcraftPlan).mockResolvedValue({ data: plan, usage: { inputTokens: 0, outputTokens: 0, totalTokens: 0, estimatedCostUsd: 0 } });
  render(<ShotcraftPlannerDialog open settings={settings} onOpenChange={vi.fn()} onNeedSettings={vi.fn()} />);
  fireEvent.change(screen.getByRole("textbox", { name: "视频内容与镜头要求" }), { target: { value: "介绍产品" } });
  fireEvent.click(screen.getByRole("button", { name: "生成分镜" }));
  expect(await screen.findByText("产品标题 · 4.00 秒")).toBeVisible();
  expect(useEditorStore.getState().past).toHaveLength(0);
  fireEvent.click(screen.getByRole("button", { name: "加入时间线" }));
  expect(useEditorStore.getState().past).toHaveLength(1);
  act(() => useEditorStore.getState().undo());
  expect(useEditorStore.getState().project.tracks.flatMap((track) => track.clips)).toHaveLength(0);
});
it("关闭时取消请求，过期响应不能恢复旧计划", async () => {
  let resolve: ((value: Awaited<ReturnType<typeof generateShotcraftPlan>>) => void) | undefined;
  vi.mocked(generateShotcraftPlan).mockImplementation(() => new Promise((done) => { resolve = done; }));
  const view = render(<ShotcraftPlannerDialog open settings={settings} onOpenChange={vi.fn()} onNeedSettings={vi.fn()} />);
  fireEvent.change(screen.getByRole("textbox", { name: "视频内容与镜头要求" }), { target: { value: "内容" } });
  fireEvent.click(screen.getByRole("button", { name: "生成分镜" }));
  await waitFor(() => expect(generateShotcraftPlan).toHaveBeenCalledTimes(1));
  const signal = vi.mocked(generateShotcraftPlan).mock.calls[0][2];
  view.rerender(<ShotcraftPlannerDialog open={false} settings={settings} onOpenChange={vi.fn()} onNeedSettings={vi.fn()} />);
  expect(signal?.aborted).toBe(true);
  await act(async () => { resolve?.({ data: plan, usage: { inputTokens: 0, outputTokens: 0, totalTokens: 0, estimatedCostUsd: 0 } }); });
  view.rerender(<ShotcraftPlannerDialog open settings={settings} onOpenChange={vi.fn()} onNeedSettings={vi.fn()} />);
  expect(screen.getByRole("button", { name: "加入时间线" })).toBeDisabled();
});
